In [ ]:
import pandas as pd

# اقرأ ملف المكالمات
df = pd.read_excel("Telecom Company Call-Center-Dataset.xlsx")   # غير الاسم لو الملف اسمه مختلف

# معلومات عن الداتا
print(df.info())

print("=" * 80)

# أول 5 صفوف
display(df.head())

print("=" * 80)

# عدد الصفوف والأعمدة
print("Shape:", df.shape)

print("=" * 80)

# أسماء الأعمدة
print(df.columns.tolist())

print("=" * 80)

# عدد الـ Agents الحاليين
print("Unique Agents:", df["Agent"].nunique())

print(df["Agent"].unique())

In [1]:
import pandas as pd
print(pd.__version__)

3.0.1

In [2]:
import pandas as pd
import random
import string
from faker import Faker

In [3]:
import pandas as pd

# اقرأ ملف المكالمات
df = pd.read_excel("Telecom Company Call-Center-Dataset.xlsx")   # غير الاسم لو الملف اسمه مختلف

# معلومات عن الداتا
print(df.info())

print("=" * 80)

# أول 5 صفوف
display(df.head())

print("=" * 80)

# عدد الصفوف والأعمدة
print("Shape:", df.shape)

print("=" * 80)

# أسماء الأعمدة
print(df.columns.tolist())

print("=" * 80)

# عدد الـ Agents الحاليين
print("Unique Agents:", df["Agent"].nunique())

print(df["Agent"].unique())

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Call Id                     5000 non-null   str
 1   Agent                       5000 non-null   str
 2   Date                        5000 non-null   str
 3   Time                        5000 non-null   object
 4   Topic                       5000 non-null   str
 5   Answered (Y/N)              5000 non-null   str
 6   Resolved                    5000 non-null   str
 7   Speed of answer in seconds  4054 non-null   float64
 8   AvgTalkDuration             4054 non-null   object
 9   Satisfaction rating         4054 non-null   float64
dtypes: float64(2), object(2), str(6)
memory usage: 390.8+ KB
None
================================================================================

,Call Id,Agent,Date,Time,Topic,Answered (Y/N),Resolved,Speed of answer in seconds,AvgTalkDuration,Satisfaction rating
0,ID0001,Diane,2021-01-01,09:12:58,Contract related,Y,Y,109.0,00:02:23,3.0
1,ID0002,Becky,2021-01-01,09:12:58,Technical Support,Y,N,70.0,00:04:02,3.0
2,ID0003,Stewart,2021-01-01,09:47:31,Contract related,Y,Y,10.0,00:02:11,3.0
3,ID0004,Greg,2021-01-01,09:47:31,Contract related,Y,Y,53.0,00:00:37,2.0
4,ID0005,Becky,2021-01-01,10:00:29,Payment related,Y,Y,95.0,00:01:00,3.0

================================================================================
Shape: (5000, 10)
================================================================================
['Call Id', 'Agent', 'Date', 'Time', 'Topic', 'Answered (Y/N)', 'Resolved', 'Speed of answer in seconds', 'AvgTalkDuration', 'Satisfaction rating']
================================================================================
Unique Agents: 8
<StringArray>
['Diane', 'Becky', 'Stewart', 'Greg', 'Jim', 'Joe', 'Martha', 'Dan']
Length: 8, dtype: str

In [4]:
print("Unique Agents:", df["Agent"].nunique())
print(df["Agent"].unique())

Unique Agents: 8
<StringArray>
['Diane', 'Becky', 'Stewart', 'Greg', 'Jim', 'Joe', 'Martha', 'Dan']
Length: 8, dtype: str

In [5]:
import pandas as pd

# قراءة الملف
df = pd.read_excel("Telecom Company Call-Center-Dataset.xlsx")

# أسماء الـ Agents
agents = sorted(df["Agent"].unique())

print(f"Number of Agents: {len(agents)}")
print(agents)

Number of Agents: 8
['Becky', 'Dan', 'Diane', 'Greg', 'Jim', 'Joe', 'Martha', 'Stewart']

In [6]:
# أسماء جديدة للـ 8 Agents

new_agents = {
    "Becky": "Ahmed Mohamed",
    "Dan": "Omar Hassan",
    "Diane": "Sara Ali",
    "Greg": "Mostafa Ahmed",
    "Jim": "Youssef Samir",
    "Joe": "Mahmoud Adel",
    "Martha": "Menna Wael",
    "Stewart": "Karim Nabil"
}

# استبدال الأسماء
df["Agent"] = df["Agent"].replace(new_agents)

# عرض الأسماء الجديدة
print(df["Agent"].unique())

<StringArray>
[     'Sara Ali', 'Ahmed Mohamed',   'Karim Nabil', 'Mostafa Ahmed',
 'Youssef Samir',  'Mahmoud Adel',    'Menna Wael',   'Omar Hassan']
Length: 8, dtype: str

In [7]:
# استخراج أسماء الـ Agents بعد التعديل
agents = sorted(df["Agent"].unique())

# إنشاء AgentID
agent_ids = {
    agent: f"AG{i:03}"
    for i, agent in enumerate(agents, start=1)
}

# إضافة العمود
df["AgentID"] = df["Agent"].map(agent_ids)

# نخلي AgentID بعد Call ID مباشرة
cols = list(df.columns)

cols.remove("AgentID")

call_index = cols.index("Call Id") + 1

cols.insert(call_index, "AgentID")

df = df[cols]

display(df.head())

,Call Id,AgentID,Agent,Date,Time,Topic,Answered (Y/N),Resolved,Speed of answer in seconds,AvgTalkDuration,Satisfaction rating
0,ID0001,AG007,Sara Ali,2021-01-01,09:12:58,Contract related,Y,Y,109.0,00:02:23,3.0
1,ID0002,AG001,Ahmed Mohamed,2021-01-01,09:12:58,Technical Support,Y,N,70.0,00:04:02,3.0
2,ID0003,AG002,Karim Nabil,2021-01-01,09:47:31,Contract related,Y,Y,10.0,00:02:11,3.0
3,ID0004,AG005,Mostafa Ahmed,2021-01-01,09:47:31,Contract related,Y,Y,53.0,00:00:37,2.0
4,ID0005,AG001,Ahmed Mohamed,2021-01-01,10:00:29,Payment related,Y,Y,95.0,00:01:00,3.0

In [8]:
df.to_excel("CallCenter_Step1.xlsx", index=False)

In [9]:
# إنشاء جدول الموظفين

dim_agents = (
    df[["AgentID", "Agent"]]
    .drop_duplicates()
    .sort_values("AgentID")
    .reset_index(drop=True)
)

dim_agents

  AgentID          Agent
0   AG001  Ahmed Mohamed
1   AG002    Karim Nabil
2   AG003   Mahmoud Adel
3   AG004     Menna Wael
4   AG005  Mostafa Ahmed
5   AG006    Omar Hassan
6   AG007       Sara Ali
7   AG008  Youssef Samir

In [10]:
dim_agents["Hire Date"] = pd.to_datetime("2021-01-01")

dim_agents["Exit Date"] = pd.NaT

dim_agents

  AgentID          Agent  Hire Date Exit Date
0   AG001  Ahmed Mohamed 2021-01-01       NaT
1   AG002    Karim Nabil 2021-01-01       NaT
2   AG003   Mahmoud Adel 2021-01-01       NaT
3   AG004     Menna Wael 2021-01-01       NaT
4   AG005  Mostafa Ahmed 2021-01-01       NaT
5   AG006    Omar Hassan 2021-01-01       NaT
6   AG007       Sara Ali 2021-01-01       NaT
7   AG008  Youssef Samir 2021-01-01       NaT

In [11]:
dim_agents.to_excel("Dim_Agents_Step1.xlsx", index=False)

In [12]:
import random

# -----------------------------
# First Names
# -----------------------------

first_names = [
    "Ahmed","Mohamed","Omar","Youssef","Mahmoud","Mostafa","Karim","Hassan",
    "Ali","Amr","Ibrahim","Khaled","Tarek","Sherif","Wael","Ayman","Hossam",
    "Eslam","Adel","Samir","Nour","Sara","Mona","Menna","Aya","Nada",
    "Heba","Fatma","Salma","Mariam","Reem","Laila","Dina","Doaa","Nesma",
    "Shimaa","Rania","Esraa","Habiba","Malak"
]

# -----------------------------
# Last Names
# -----------------------------

last_names = [
    "Mohamed","Ahmed","Ali","Hassan","Mahmoud","Samir","Nabil","Adel",
    "Mostafa","Ibrahim","Wael","Khaled","Tarek","Sherif","Ayman","Sayed",
    "Gamal","Fathy","Salem","Youssef","Saad","Reda","Ashraf","Farouk",
    "Hamdy","Abdelrahman","Fouad","Shaban","Soliman","Magdy"
]

In [13]:
def generate_name():
    return f"{random.choice(first_names)} {random.choice(last_names)}"

In [14]:
for _ in range(10):
    print(generate_name())

Ali Shaban
Habiba Magdy
Ayman Ayman
Shimaa Farouk
Adel Tarek
Wael Adel
Sherif Reda
Esraa Farouk
Nada Sherif
Mahmoud Ayman

In [15]:
male_first_names = [
    "Ahmed","Mohamed","Mahmoud","Mostafa","Omar","Youssef","Karim","Hassan",
    "Ali","Amr","Ibrahim","Khaled","Tarek","Sherif","Wael","Ayman","Hossam",
    "Eslam","Adel","Samir","Nour","Mina","Fady","Bishoy","Rami","Mazen",
    "Ziad","Alaa","Shady","Islam","Hamza","Anas","Osama","Marwan","Hazem"
]

In [16]:
female_first_names = [
    "Sara","Mona","Menna","Aya","Nada","Heba","Fatma","Salma","Mariam",
    "Reem","Laila","Dina","Doaa","Nesma","Shimaa","Rania","Esraa",
    "Habiba","Malak","Farah","Yara","Rana","Asmaa","Noha","Mai"
]

In [17]:
last_names = [
    "Mohamed","Ahmed","Ali","Hassan","Mahmoud","Samir","Nabil",
    "Adel","Mostafa","Ibrahim","Wael","Khaled","Tarek","Sherif",
    "Ayman","Sayed","Gamal","Fathy","Salem","Youssef","Saad",
    "Reda","Ashraf","Farouk","Hamdy","Fouad","Shaban","Soliman",
    "Magdy","Abdelrahman"
]

In [18]:
import random

def generate_name(gender):

    if gender == "Male":
        first = random.choice(male_first_names)
    else:
        first = random.choice(female_first_names)

    last = random.choice(last_names)

    return f"{first} {last}"

In [19]:
for i in range(10):

    gender = random.choices(
        ["Male","Female"],
        weights=[65,35]
    )[0]

    print(gender,"-",generate_name(gender))

Female - Rana Ali
Male - Ibrahim Abdelrahman
Male - Youssef Reda
Male - Mahmoud Fouad
Male - Khaled Ali
Female - Reem Ibrahim
Male - Omar Samir
Male - Sherif Magdy
Male - Khaled Shaban
Male - Hassan Shaban

In [20]:
import random
import pandas as pd

random.seed(42)

# ==========================
# الموظفين الحاليين
# ==========================

current_agents = dim_agents.copy()

# ==========================
# أسماء الفرق
# ==========================

teams = [
    "Team A",
    "Team B",
    "Team C",
    "Team D",
    "Team E",
    "Team F",
    "Team G",
    "Team H",
    "Team I",
    "Team J"
]

# ==========================
# Team Leaders
# ==========================

team_leaders = [
    "Mohamed Hassan",
    "Ahmed Mostafa",
    "Omar Ali",
    "Sara Ahmed",
    "Mahmoud Adel",
    "Mona Samir",
    "Youssef Khaled",
    "Nada Ashraf",
    "Karim Nabil",
    "Menna Wael"
]

In [21]:
def create_agent(agent_id, hire_date):

    gender = random.choices(
        ["Male", "Female"],
        weights=[65,35]
    )[0]

    name = generate_name(gender)

    return {
        "AgentID": agent_id,
        "Agent": name,
        "Gender": gender,
        "Hire Date": hire_date,
        "Exit Date": pd.NaT
    }

In [22]:
new_agents = []

# ------------------------
# سنة 2022
# ------------------------

for i in range(9,46):

    hire = pd.Timestamp(2022,
                        random.randint(1,12),
                        random.randint(1,28))

    new_agents.append(
        create_agent(f"AG{i:03}",hire)
    )

# ------------------------
# سنة 2023
# ------------------------

for i in range(46,101):

    hire = pd.Timestamp(2023,
                        random.randint(1,12),
                        random.randint(1,28))

    new_agents.append(
        create_agent(f"AG{i:03}",hire)
    )

new_agents = pd.DataFrame(new_agents)

new_agents.head()

  AgentID            Agent  Gender  Hire Date Exit Date
0   AG009       Eslam Adel    Male 2022-11-04       NaT
1   AG010      Rana Farouk  Female 2022-04-05       NaT
2   AG011  Mahmoud Mohamed    Male 2022-09-03       NaT
3   AG012    Mohamed Fathy    Male 2022-02-07       NaT
4   AG013     Hazem Sherif    Male 2022-04-23       NaT

In [23]:
# إضافة Gender للأصليين

gender_map = {
    "Ahmed Mohamed":"Male",
    "Karim Nabil":"Male",
    "Sara Ali":"Female",
    "Mostafa Ahmed":"Male",
    "Youssef Samir":"Male",
    "Mahmoud Adel":"Male",
    "Menna Wael":"Female",
    "Omar Hassan":"Male"
}

current_agents["Gender"] = current_agents["Agent"].map(gender_map)

# دمج الجدولين

dim_agents = pd.concat(
    [current_agents,new_agents],
    ignore_index=True
)

dim_agents

   AgentID          Agent  Hire Date Exit Date  Gender
0    AG001  Ahmed Mohamed 2021-01-01       NaT    Male
1    AG002    Karim Nabil 2021-01-01       NaT    Male
2    AG003   Mahmoud Adel 2021-01-01       NaT    Male
3    AG004     Menna Wael 2021-01-01       NaT  Female
4    AG005  Mostafa Ahmed 2021-01-01       NaT    Male
..     ...            ...        ...       ...     ...
95   AG096  Nesma Mohamed 2023-03-26       NaT  Female
96   AG097    Nesma Fouad 2023-03-24       NaT  Female
97   AG098  Salma Mostafa 2023-11-28       NaT  Female
98   AG099   Doaa Soliman 2023-03-26       NaT  Female
99   AG100   Tarek Shaban 2023-01-28       NaT    Male

[100 rows x 5 columns]

In [24]:
print(dim_agents.shape)

display(dim_agents.head())

display(dim_agents.tail())

(100, 5)

  AgentID          Agent  Hire Date Exit Date  Gender
0   AG001  Ahmed Mohamed 2021-01-01       NaT    Male
1   AG002    Karim Nabil 2021-01-01       NaT    Male
2   AG003   Mahmoud Adel 2021-01-01       NaT    Male
3   AG004     Menna Wael 2021-01-01       NaT  Female
4   AG005  Mostafa Ahmed 2021-01-01       NaT    Male

   AgentID          Agent  Hire Date Exit Date  Gender
95   AG096  Nesma Mohamed 2023-03-26       NaT  Female
96   AG097    Nesma Fouad 2023-03-24       NaT  Female
97   AG098  Salma Mostafa 2023-11-28       NaT  Female
98   AG099   Doaa Soliman 2023-03-26       NaT  Female
99   AG100   Tarek Shaban 2023-01-28       NaT    Male

In [25]:
# كل الموظفين في البداية Active

dim_agents["Employment Status"] = "Active"

In [26]:
team_leaders = {
    "Team A": "Mohamed Hassan",
    "Team B": "Ahmed Mostafa",
    "Team C": "Omar Ali",
    "Team D": "Sara Ahmed",
    "Team E": "Mahmoud Adel",
    "Team F": "Mona Samir",
    "Team G": "Youssef Khaled",
    "Team H": "Nada Ashraf",
    "Team I": "Karim Nabil",
    "Team J": "Menna Wael"
}

In [27]:
dim_agents["Hire Year"] = dim_agents["Hire Date"].dt.year

In [28]:
dim_agents["Team"] = None
dim_agents["Team Leader"] = None

In [29]:
teams = [
    "Team A","Team B","Team C","Team D","Team E",
    "Team F","Team G","Team H","Team I","Team J"
]

leaders = {
    "Team A":"Mohamed Hassan",
    "Team B":"Ahmed Mostafa",
    "Team C":"Omar Ali",
    "Team D":"Sara Ahmed",
    "Team E":"Mahmoud Adel",
    "Team F":"Mona Samir",
    "Team G":"Youssef Khaled",
    "Team H":"Nada Ashraf",
    "Team I":"Karim Nabil",
    "Team J":"Menna Wael"
}

In [30]:
# ===========================
# توزيع الموظفين على الفرق
# ===========================

# 2021
mask = dim_agents["Hire Year"] == 2021

dim_agents.loc[mask, "Team"] = "Team A"
dim_agents.loc[mask, "Team Leader"] = leaders["Team A"]


# 2022
mask = dim_agents["Hire Year"] == 2022

idx = dim_agents.loc[mask].index.tolist()

for i, index in enumerate(idx):

    team = teams[i // 9]

    dim_agents.loc[index, "Team"] = team
    dim_agents.loc[index, "Team Leader"] = leaders[team]


# 2023
mask = dim_agents["Hire Year"] == 2023

idx = dim_agents.loc[mask].index.tolist()

for i, index in enumerate(idx):

    team = teams[i // 10]

    dim_agents.loc[index, "Team"] = team
    dim_agents.loc[index, "Team Leader"] = leaders[team]

In [31]:
dim_agents.groupby(
    ["Hire Year","Team"]
).size()

Hire Year  Team
2021       Team A     8
2022       Team A     9
           Team B     9
           Team C     9
           Team D     9
           Team E     1
2023       Team A    10
           Team B    10
           Team C    10
           Team D    10
           Team E    10
           Team F     5
dtype: int64

In [32]:
dim_agents["Employment Status"] = "Active"
dim_agents["Hire Year"] = dim_agents["Hire Date"].dt.year

In [33]:
teams = {
    "Team A": "Mohamed Hassan",
    "Team B": "Ahmed Mostafa",
    "Team C": "Omar Ali",
    "Team D": "Sara Ahmed",
    "Team E": "Mahmoud Adel",
    "Team F": "Mona Samir",
    "Team G": "Youssef Khaled",
    "Team H": "Nada Ashraf",
    "Team I": "Karim Nabil",
    "Team J": "Menna Wael"
}

In [34]:
dim_agents["Team"] = None
dim_agents["Team Leader"] = None

In [35]:
team_names = list(teams.keys())

for i in range(len(dim_agents)):

    team_index = i // 10

    team = team_names[team_index]

    dim_agents.loc[i, "Team"] = team
    dim_agents.loc[i, "Team Leader"] = teams[team]

In [36]:
import random

random.seed(42)

In [37]:
agents_2021 = dim_agents[
    dim_agents["Hire Year"] == 2021
].index.tolist()

# اختيار 2 للاستقالة

resigned_2021 = random.sample(agents_2021,2)

resigned_2021

[1, 0]

In [38]:
agents_2022 = dim_agents[
    dim_agents["Hire Year"] == 2022
].index.tolist()

# اختيار 10 للاستقالة

resigned_2022 = random.sample(agents_2022,10)

len(resigned_2022)

10

In [39]:
# استقالات 2021
for idx in resigned_2021:

    dim_agents.loc[idx,"Employment Status"] = "Resigned"

    dim_agents.loc[idx,"Exit Date"] = pd.Timestamp(
        2022,
        random.randint(1,12),
        random.randint(1,28)
    )


# استقالات 2022
for idx in resigned_2022:

    dim_agents.loc[idx,"Employment Status"] = "Resigned"

    dim_agents.loc[idx,"Exit Date"] = pd.Timestamp(
        2023,
        random.randint(1,12),
        random.randint(1,28)
    )

In [40]:
print(dim_agents["Employment Status"].value_counts())

print("="*50)

display(dim_agents.head(15))

Employment Status
Active      88
Resigned    12
Name: count, dtype: int64
==================================================

,AgentID,Agent,Hire Date,Exit Date,Gender,Employment Status,Hire Year,Team,Team Leader
0,AG001,Ahmed Mohamed,2021-01-01,2022-04-17,Male,Resigned,2021,Team A,Mohamed Hassan
1,AG002,Karim Nabil,2021-01-01,2022-02-07,Male,Resigned,2021,Team A,Mohamed Hassan
2,AG003,Mahmoud Adel,2021-01-01,NaT,Male,Active,2021,Team A,Mohamed Hassan
3,AG004,Menna Wael,2021-01-01,NaT,Female,Active,2021,Team A,Mohamed Hassan
4,AG005,Mostafa Ahmed,2021-01-01,NaT,Male,Active,2021,Team A,Mohamed Hassan
5,AG006,Omar Hassan,2021-01-01,NaT,Male,Active,2021,Team A,Mohamed Hassan
6,AG007,Sara Ali,2021-01-01,NaT,Female,Active,2021,Team A,Mohamed Hassan
7,AG008,Youssef Samir,2021-01-01,NaT,Male,Active,2021,Team A,Mohamed Hassan
8,AG009,Eslam Adel,2022-11-04,2023-07-11,Male,Resigned,2022,Team A,Mohamed Hassan
9,AG010,Rana Farouk,2022-04-05,2023-03-23,Female,Resigned,2022,Team A,Mohamed Hassan
10,AG011,Mahmoud Mohamed,2022-09-03,NaT,Male,Active,2022,Team B,Ahmed Mostafa
11,AG012,Mohamed Fathy,2022-02-07,NaT,Male,Active,2022,Team B,Ahmed Mostafa
12,AG013,Hazem Sherif,2022-04-23,NaT,Male,Active,2022,Team B,Ahmed Mostafa
13,AG014,Ahmed Hamdy,2022-04-15,2023-08-19,Male,Resigned,2022,Team B,Ahmed Mostafa
14,AG015,Eslam Mahmoud,2022-03-23,2023-07-08,Male,Resigned,2022,Team B,Ahmed Mostafa

In [41]:
def generate_call_id(number):

    return f"CA{number:06}"

In [42]:
for i in range(1,6):

    print(generate_call_id(i))

CA000001
CA000002
CA000003
CA000004
CA000005

In [43]:
df = df.reset_index(drop=True)

df["Call Id"] = [
    generate_call_id(i)
    for i in range(1,len(df)+1)
]

In [44]:
df.head()

,Call Id,AgentID,Agent,Date,Time,Topic,Answered (Y/N),Resolved,Speed of answer in seconds,AvgTalkDuration,Satisfaction rating
0,CA000001,AG007,Sara Ali,2021-01-01,09:12:58,Contract related,Y,Y,109.0,00:02:23,3.0
1,CA000002,AG001,Ahmed Mohamed,2021-01-01,09:12:58,Technical Support,Y,N,70.0,00:04:02,3.0
2,CA000003,AG002,Karim Nabil,2021-01-01,09:47:31,Contract related,Y,Y,10.0,00:02:11,3.0
3,CA000004,AG005,Mostafa Ahmed,2021-01-01,09:47:31,Contract related,Y,Y,53.0,00:00:37,2.0
4,CA000005,AG001,Ahmed Mohamed,2021-01-01,10:00:29,Payment related,Y,Y,95.0,00:01:00,3.0

In [45]:
fact_2021 = df.copy()

In [46]:
fact_2021["Date"] = pd.to_datetime(fact_2021["Date"])

In [47]:
fact_2021 = fact_2021.merge(
    dim_agents[
        [
            "AgentID",
            "Agent",
            "Team",
            "Team Leader",
            "Hire Date",
            "Exit Date",
            "Employment Status"
        ]
    ],
    on="Agent",
    how="left"
)

In [48]:
fact_2021 = fact_2021[
[
"Call Id",
"AgentID",
"Agent",
"Team",
"Team Leader",
"Date",
"Time",
"Topic",
"Answered (Y/N)",
"Resolved",
"Speed of answer in seconds",
"AvgTalkDuration",
"Satisfaction rating",
"Hire Date",
"Exit Date",
"Employment Status"
]
]

KeyError: "['AgentID'] not in index"

In [49]:
print(dim_agents.columns.tolist())

['AgentID', 'Agent', 'Hire Date', 'Exit Date', 'Gender', 'Employment Status', 'Hire Year', 'Team', 'Team Leader']

In [50]:
print(fact_2021.columns.tolist())

['Call Id', 'AgentID_x', 'Agent', 'Date', 'Time', 'Topic', 'Answered (Y/N)', 'Resolved', 'Speed of answer in seconds', 'AvgTalkDuration', 'Satisfaction rating', 'AgentID_y', 'Team', 'Team Leader', 'Hire Date', 'Exit Date', 'Employment Status']

In [51]:
(fact_2021["AgentID_x"] == fact_2021["AgentID_y"]).all()

np.True_

In [52]:
fact_2021 = fact_2021.drop(columns=["AgentID_y"])

fact_2021 = fact_2021.rename(
    columns={
        "AgentID_x":"AgentID"
    }
)

In [53]:
fact_2021 = df.merge(
    dim_agents[
        [
            "Agent",
            "Team",
            "Team Leader",
            "Hire Date",
            "Exit Date",
            "Employment Status"
        ]
    ],
    on="Agent",
    how="left"
)

In [54]:
print("Total Agents:", len(dim_agents))

Total Agents: 100

In [55]:
print(dim_agents["AgentID"].nunique())

100

In [56]:
print(dim_agents["AgentID"].duplicated().sum())

0

In [57]:
print(dim_agents["Agent"].duplicated().sum())

2

In [58]:
dim_agents.groupby("Hire Year").size()

Hire Year
2021     8
2022    37
2023    55
dtype: int64

In [59]:
dim_agents["Team"].value_counts().sort_index()

Team
Team A    10
Team B    10
Team C    10
Team D    10
Team E    10
Team F    10
Team G    10
Team H    10
Team I    10
Team J    10
Name: count, dtype: int64

In [60]:
dim_agents.groupby("Team")["Team Leader"].nunique()

Team
Team A    1
Team B    1
Team C    1
Team D    1
Team E    1
Team F    1
Team G    1
Team H    1
Team I    1
Team J    1
Name: Team Leader, dtype: int64

In [61]:
dim_agents["Team Leader"].value_counts()

Team Leader
Mohamed Hassan    10
Ahmed Mostafa     10
Omar Ali          10
Sara Ahmed        10
Mahmoud Adel      10
Mona Samir        10
Youssef Khaled    10
Nada Ashraf       10
Karim Nabil       10
Menna Wael        10
Name: count, dtype: int64

In [62]:
dim_agents["Employment Status"].value_counts()

Employment Status
Active      88
Resigned    12
Name: count, dtype: int64

In [63]:
dim_agents.groupby("Employment Status")["Exit Date"].apply(lambda x: x.isna().sum())

Employment Status
Active      88
Resigned     0
Name: Exit Date, dtype: int64

In [64]:
# أي Active عنده Exit Date؟ (المفروض صفر)
print(
    dim_agents[
        (dim_agents["Employment Status"] == "Active") &
        (dim_agents["Exit Date"].notna())
    ].shape[0]
)

# أي Resigned معندوش Exit Date؟ (المفروض صفر)
print(
    dim_agents[
        (dim_agents["Employment Status"] == "Resigned") &
        (dim_agents["Exit Date"].isna())
    ].shape[0]
)

0
0

In [65]:
dim_agents.sample(10)

,AgentID,Agent,Hire Date,Exit Date,Gender,Employment Status,Hire Year,Team,Team Leader
27,AG028,Nour Nabil,2022-05-03,NaT,Male,Active,2022,Team C,Omar Ali
38,AG039,Yara Ibrahim,2022-03-17,NaT,Female,Active,2022,Team D,Sara Ahmed
96,AG097,Nesma Fouad,2023-03-24,NaT,Female,Active,2023,Team J,Menna Wael
99,AG100,Tarek Shaban,2023-01-28,NaT,Male,Active,2023,Team J,Menna Wael
61,AG062,Omar Ayman,2023-05-15,NaT,Male,Active,2023,Team G,Youssef Khaled
67,AG068,Mostafa Salem,2023-04-10,NaT,Male,Active,2023,Team G,Youssef Khaled
49,AG050,Ayman Adel,2023-08-17,NaT,Male,Active,2023,Team E,Mahmoud Adel
41,AG042,Mohamed Hassan,2022-01-20,NaT,Male,Active,2022,Team E,Mahmoud Adel
10,AG011,Mahmoud Mohamed,2022-09-03,NaT,Male,Active,2022,Team B,Ahmed Mostafa
74,AG075,Nour Adel,2023-06-09,NaT,Male,Active,2023,Team H,Nada Ashraf

In [66]:
dim_agents.groupby("Hire Year")["Team Leader"].nunique()

Hire Year
2021    1
2022    5
2023    6
Name: Team Leader, dtype: int64

In [67]:
end_2021 = dim_agents[
    dim_agents["Hire Date"] <= "2021-12-31"
]

print(end_2021["Team"].value_counts())
print(end_2021["Team Leader"].value_counts())

Team
Team A    8
Name: count, dtype: int64
Team Leader
Mohamed Hassan    8
Name: count, dtype: int64

In [68]:
end_2022 = dim_agents[
    dim_agents["Hire Date"] <= "2022-12-31"
]

print(end_2022["Team"].value_counts().sort_index())
print("="*40)
print(end_2022["Team Leader"].value_counts())

Team
Team A    10
Team B    10
Team C    10
Team D    10
Team E     5
Name: count, dtype: int64
========================================
Team Leader
Mohamed Hassan    10
Ahmed Mostafa     10
Omar Ali          10
Sara Ahmed        10
Mahmoud Adel       5
Name: count, dtype: int64

In [69]:
fact_2021 = df.copy()

In [70]:
fact_2021["Date"] = pd.to_datetime(fact_2021["Date"])

In [71]:
print(fact_2021["Date"].min())
print(fact_2021["Date"].max())

2021-01-01 00:00:00
2021-03-31 00:00:00

In [72]:
import random

random.seed(42)

def get_active_agents(year):
    """
    ترجع كل الموظفين النشطين خلال سنة معينة
    """

    agents = dim_agents[
        (dim_agents["Hire Date"].dt.year <= year)
        &
        (
            (dim_agents["Exit Date"].isna())
            |
            (dim_agents["Exit Date"].dt.year >= year)
        )
    ].copy()

    return agents

In [73]:
print(len(get_active_agents(2021)))

print(len(get_active_agents(2022)))

print(len(get_active_agents(2023)))

8
45
98

In [74]:
print(fact_2021.dtypes)

Call Id                                  str
AgentID                                  str
Agent                                    str
Date                          datetime64[us]
Time                                  object
Topic                                    str
Answered (Y/N)                           str
Resolved                                 str
Speed of answer in seconds           float64
AvgTalkDuration                       object
Satisfaction rating                  float64
dtype: object

In [75]:
print(fact_2021.shape)

print(fact_2021["Date"].min())
print(fact_2021["Date"].max())

print(fact_2021["Agent"].nunique())

print(fact_2021["Call Id"].nunique())

(5000, 11)
2021-01-01 00:00:00
2021-03-31 00:00:00
8
5000

In [76]:
def change_year(date_value, new_year):
    """
    تغيير السنة مع الحفاظ على الشهر واليوم
    """

    return date_value.replace(year=new_year)

In [77]:
print(change_year(pd.Timestamp("2021-05-17"), 2022))

print(change_year(pd.Timestamp("2021-12-31"), 2023))

2022-05-17 00:00:00
2023-12-31 00:00:00

In [78]:
def get_available_agents(call_date):

    agents = dim_agents[
        (dim_agents["Hire Date"] <= call_date)
        &
        (
            (dim_agents["Exit Date"].isna())
            |
            (dim_agents["Exit Date"] >= call_date)
        )
    ]

    return agents

In [79]:
agents = get_available_agents(
    pd.Timestamp("2022-06-15")
)

print(len(agents))

display(agents.head())

28

,AgentID,Agent,Hire Date,Exit Date,Gender,Employment Status,Hire Year,Team,Team Leader
2,AG003,Mahmoud Adel,2021-01-01,NaT,Male,Active,2021,Team A,Mohamed Hassan
3,AG004,Menna Wael,2021-01-01,NaT,Female,Active,2021,Team A,Mohamed Hassan
4,AG005,Mostafa Ahmed,2021-01-01,NaT,Male,Active,2021,Team A,Mohamed Hassan
5,AG006,Omar Hassan,2021-01-01,NaT,Male,Active,2021,Team A,Mohamed Hassan
6,AG007,Sara Ali,2021-01-01,NaT,Female,Active,2021,Team A,Mohamed Hassan

In [80]:
print(len(get_available_agents(pd.Timestamp("2021-03-01"))))

print(len(get_available_agents(pd.Timestamp("2022-12-01"))))

print(len(get_available_agents(pd.Timestamp("2023-12-01"))))

8
40
87

In [81]:
def active_agents_in_month(year, month):

    end_of_month = pd.Timestamp(year, month, 1) + pd.offsets.MonthEnd(0)

    agents = dim_agents[
        (dim_agents["Hire Date"] <= end_of_month)
        &
        (
            (dim_agents["Exit Date"].isna())
            |
            (dim_agents["Exit Date"] >= end_of_month)
        )
    ]

    return agents

In [82]:
for month in range(1,13):

    print(
        month,
        len(active_agents_in_month(2022, month))
    )

1 12
2 13
3 16
4 22
5 27
6 29
7 31
8 32
9 33
10 34
11 40
12 43

In [83]:
def calculate_weight(agent_row, call_date):
    """
    حساب وزن الموظف حسب خبرته وقت المكالمة
    """

    experience_days = (call_date - agent_row["Hire Date"]).days

    if experience_days < 90:
        return 1.0

    elif experience_days < 180:
        return 1.2

    elif experience_days < 365:
        return 1.5

    else:
        return 2.0

In [84]:
def choose_agent(call_date):

    available = get_available_agents(call_date).copy()

    available["Weight"] = available.apply(
        lambda row: calculate_weight(row, call_date),
        axis=1
    )

    selected = random.choices(
        population=available.to_dict("records"),
        weights=available["Weight"],
        k=1
    )[0]

    return selected

In [85]:
for i in range(10):

    agent = choose_agent(
        pd.Timestamp("2022-10-15")
    )

    print(
        agent["AgentID"],
        agent["Agent"],
        agent["Hire Date"].date(),
        agent["Team"]
    )

AG027 Laila Tarek 2022-01-08 Team C
AG003 Mahmoud Adel 2021-01-01 Team A
AG010 Rana Farouk 2022-04-05 Team A
AG008 Youssef Samir 2021-01-01 Team A
AG032 Youssef Hamdy 2022-04-05 Team D
AG028 Nour Nabil 2022-05-03 Team C
AG041 Esraa Abdelrahman 2022-03-18 Team E
AG005 Mostafa Ahmed 2021-01-01 Team A
AG016 Youssef Tarek 2022-04-25 Team B
AG003 Mahmoud Adel 2021-01-01 Team A

In [86]:
def get_month_template(df, month):
    """
    ترجع كل مكالمات شهر معين من Dataset 2021
    """

    return df[df["Date"].dt.month == month].copy()

In [87]:
for month in range(1, 13):

    calls = get_month_template(fact_2021, month)

    print(
        f"Month {month}: {len(calls)} Calls"
    )

Month 1: 1772 Calls
Month 2: 1616 Calls
Month 3: 1612 Calls
Month 4: 0 Calls
Month 5: 0 Calls
Month 6: 0 Calls
Month 7: 0 Calls
Month 8: 0 Calls
Month 9: 0 Calls
Month 10: 0 Calls
Month 11: 0 Calls
Month 12: 0 Calls

In [88]:
def monthly_active_agents(year):
    """
    ترجع عدد الموظفين النشطين في نهاية كل شهر
    """

    data = []

    for month in range(1, 13):

        agents = active_agents_in_month(year, month)

        data.append({
            "Year": year,
            "Month": month,
            "Active Agents": len(agents)
        })

    return pd.DataFrame(data)

In [89]:
active_2022 = monthly_active_agents(2022)

display(active_2022)

    Year  Month  Active Agents
0   2022      1             12
1   2022      2             13
2   2022      3             16
3   2022      4             22
4   2022      5             27
5   2022      6             29
6   2022      7             31
7   2022      8             32
8   2022      9             33
9   2022     10             34
10  2022     11             40
11  2022     12             43

In [98]:
CALLS_PER_AGENT = 220

In [91]:
def calculate_monthly_calls(active_df):

    active_df = active_df.copy()

    active_df["Target Calls"] = (
        active_df["Active Agents"] * CALLS_PER_AGENT
    ).astype(int)

    return active_df

In [99]:
calls_2022 = calculate_monthly_calls(active_2022)

display(calls_2022)

    Year  Month  Active Agents  Target Calls
0   2022      1             12          2640
1   2022      2             13          2860
2   2022      3             16          3520
3   2022      4             22          4840
4   2022      5             27          5940
5   2022      6             29          6380
6   2022      7             31          6820
7   2022      8             32          7040
8   2022      9             33          7260
9   2022     10             34          7480
10  2022     11             40          8800
11  2022     12             43          9460

In [100]:
print("Total Calls 2022")

print(
    calls_2022["Target Calls"].sum()
)

Total Calls 2022
73040

In [94]:
# عدد الموظفين النشطين في 2021
active_2021 = len(active_agents_in_month(2021, 12))

# عدد مكالمات 2021
calls_2021 = len(fact_2021)

print("Active Agents:", active_2021)
print("Calls:", calls_2021)
print("Calls Per Agent Per Year:", round(calls_2021 / active_2021, 2))
print("Calls Per Agent Per Month:", round((calls_2021 / active_2021) / 12, 2))

Active Agents: 8
Calls: 5000
Calls Per Agent Per Year: 625.0
Calls Per Agent Per Month: 52.08

In [101]:
# توزيع مكالمات 2021 على الشهور

monthly_distribution = (
    fact_2021
    .groupby(fact_2021["Date"].dt.month)
    .size()
    .reset_index(name="Calls")
)

monthly_distribution.columns = ["Month", "Calls"]

monthly_distribution["Percentage"] = (
    monthly_distribution["Calls"] /
    monthly_distribution["Calls"].sum()
)

monthly_distribution

   Month  Calls  Percentage
0      1   1772      0.3544
1      2   1616      0.3232
2      3   1612      0.3224

In [102]:
TARGET_CALLS_2022 = 15000

monthly_distribution["Target Calls 2022"] = (
    monthly_distribution["Percentage"] * TARGET_CALLS_2022
).round().astype(int)

monthly_distribution

   Month  Calls  Percentage  Target Calls 2022
0      1   1772      0.3544               5316
1      2   1616      0.3232               4848
2      3   1612      0.3224               4836

In [103]:
TARGET_CALLS_2023 = 30000

monthly_distribution["Target Calls 2023"] = (
    monthly_distribution["Percentage"] * TARGET_CALLS_2023
).round().astype(int)

monthly_distribution

   Month  Calls  Percentage  Target Calls 2022  Target Calls 2023
0      1   1772      0.3544               5316              10632
1      2   1616      0.3232               4848               9696
2      3   1612      0.3224               4836               9672

In [104]:
print(monthly_distribution["Target Calls 2022"].sum())

print(monthly_distribution["Target Calls 2023"].sum())

15000
30000

In [105]:
def get_month_template(month):
    """
    ترجع مكالمات شهر معين من بيانات 2021
    """
    return fact_2021[
        fact_2021["Date"].dt.month == month
    ].copy()

In [106]:
jan = get_month_template(1)

print(len(jan))

display(jan.head())

1772

,Call Id,AgentID,Agent,Date,Time,Topic,Answered (Y/N),Resolved,Speed of answer in seconds,AvgTalkDuration,Satisfaction rating
0,CA000001,AG007,Sara Ali,2021-01-01,09:12:58,Contract related,Y,Y,109.0,00:02:23,3.0
1,CA000002,AG001,Ahmed Mohamed,2021-01-01,09:12:58,Technical Support,Y,N,70.0,00:04:02,3.0
2,CA000003,AG002,Karim Nabil,2021-01-01,09:47:31,Contract related,Y,Y,10.0,00:02:11,3.0
3,CA000004,AG005,Mostafa Ahmed,2021-01-01,09:47:31,Contract related,Y,Y,53.0,00:00:37,2.0
4,CA000005,AG001,Ahmed Mohamed,2021-01-01,10:00:29,Payment related,Y,Y,95.0,00:01:00,3.0

In [107]:
def expand_month(month, target_calls):
    """
    تكبير عدد مكالمات شهر معين
    """

    template = get_month_template(month)

    expanded = template.sample(
        n=target_calls,
        replace=True,
        random_state=42
    ).reset_index(drop=True)

    return expanded

In [108]:
jan_2022 = expand_month(
    1,
    monthly_distribution.loc[
        monthly_distribution["Month"] == 1,
        "Target Calls 2022"
    ].values[0]
)

print(jan_2022.shape)

display(jan_2022.head())

(5316, 11)

,Call Id,AgentID,Agent,Date,Time,Topic,Answered (Y/N),Resolved,Speed of answer in seconds,AvgTalkDuration,Satisfaction rating
0,CA001127,AG003,Mahmoud Adel,2021-01-20,17:42:43,Streaming,Y,Y,73.0,00:00:45,3.0
1,CA001460,AG001,Ahmed Mohamed,2021-01-26,17:18:14,Contract related,Y,Y,115.0,00:06:15,3.0
2,CA000861,AG002,Karim Nabil,2021-01-15,18:00:00,Admin Support,Y,Y,42.0,00:06:13,3.0
3,CA001295,AG008,Youssef Samir,2021-01-24,09:54:43,Technical Support,Y,Y,109.0,00:05:47,3.0
4,CA001131,AG003,Mahmoud Adel,2021-01-20,17:57:07,Admin Support,Y,N,100.0,00:04:04,2.0

In [109]:
def update_year(df, year):

    df = df.copy()

    df["Date"] = df["Date"].apply(
        lambda d: d.replace(year=year)
    )

    return df

In [110]:
jan_2022 = update_year(jan_2022, 2022)

print(jan_2022["Date"].min())

print(jan_2022["Date"].max())

2022-01-01 00:00:00
2022-01-31 00:00:00

In [111]:
monthly_distribution

   Month  Calls  Percentage  Target Calls 2022  Target Calls 2023
0      1   1772      0.3544               5316              10632
1      2   1616      0.3232               4848               9696
2      3   1612      0.3224               4836               9672

In [112]:
print(fact_2021["Date"].min())
print(fact_2021["Date"].max())

2021-01-01 00:00:00
2021-03-31 00:00:00

In [113]:
def change_date(date_value, new_year, new_month):
    """
    تغيير السنة والشهر مع الحفاظ على اليوم إذا أمكن.
    """

    day = min(date_value.day, 28)

    return pd.Timestamp(
        year=new_year,
        month=new_month,
        day=day
    )

In [114]:
print(change_date(pd.Timestamp("2021-01-15"), 2021, 4))

print(change_date(pd.Timestamp("2021-02-20"), 2021, 8))

print(change_date(pd.Timestamp("2021-03-31"), 2022, 12))

2021-04-15 00:00:00
2021-08-20 00:00:00
2022-12-28 00:00:00

In [115]:
def get_template_month(target_month):
    """
    يحدد شهر الـ Template المستخدم
    """

    mapping = {
        1: 1,
        2: 2,
        3: 3,
        4: 1,
        5: 2,
        6: 3,
        7: 1,
        8: 2,
        9: 3,
        10: 1,
        11: 2,
        12: 3
    }

    return mapping[target_month]

In [116]:
for m in range(1,13):
    print(m, "->", get_template_month(m))

1 -> 1
2 -> 2
3 -> 3
4 -> 1
5 -> 2
6 -> 3
7 -> 1
8 -> 2
9 -> 3
10 -> 1
11 -> 2
12 -> 3

In [117]:
def simulate_month(target_year, target_month):

    # الشهر المستخدم كـ Template
    source_month = get_template_month(target_month)

    # استخراج بيانات الشهر
    template = fact_2021[
        fact_2021["Date"].dt.month == source_month
    ].copy()

    # تغيير التاريخ فقط
    template["Date"] = template["Date"].apply(
        lambda d: change_date(
            d,
            target_year,
            target_month
        )
    )

    # خلط الصفوف
    template = template.sample(
        frac=1,
        random_state=42
    ).reset_index(drop=True)

    return template

In [118]:
april = simulate_month(2021,4)

print(april.shape)

display(
    april[
        ["Date","Time","Agent","Topic"]
    ].head()
)

(1772, 11)

        Date      Time          Agent            Topic
0 2021-04-22  14:48:29    Karim Nabil        Streaming
1 2021-04-22  11:55:41  Mostafa Ahmed  Payment related
2 2021-04-14  14:09:36     Menna Wael    Admin Support
3 2021-04-28  12:17:17       Sara Ali        Streaming
4 2021-04-21  17:11:02     Menna Wael  Payment related

In [119]:
def simulate_month(target_year, target_month, target_calls):

    # تحديد شهر الـ Template
    source_month = get_template_month(target_month)

    # استخراج بيانات الشهر
    template = fact_2021[
        fact_2021["Date"].dt.month == source_month
    ].copy()

    # تكبير عدد المكالمات
    simulated = template.sample(
        n=target_calls,
        replace=True,
        random_state=42
    ).reset_index(drop=True)

    # تغيير التاريخ
    simulated["Date"] = simulated["Date"].apply(
        lambda d: change_date(d, target_year, target_month)
    )

    # خلط الصفوف
    simulated = simulated.sample(
        frac=1,
        random_state=42
    ).reset_index(drop=True)

    return simulated

In [120]:
april = simulate_month(
    target_year=2021,
    target_month=4,
    target_calls=1800
)

print(april.shape)

display(april.head())

(1800, 11)

,Call Id,AgentID,Agent,Date,Time,Topic,Answered (Y/N),Resolved,Speed of answer in seconds,AvgTalkDuration,Satisfaction rating
0,CA001388,AG003,Mahmoud Adel,2021-04-25,14:34:05,Admin Support,Y,Y,56.0,00:03:18,3.0
1,CA000449,AG005,Mostafa Ahmed,2021-04-09,09:24:29,Payment related,Y,Y,97.0,00:02:39,5.0
2,CA000740,AG006,Omar Hassan,2021-04-13,12:37:26,Streaming,Y,Y,33.0,00:06:21,3.0
3,CA001242,AG004,Menna Wael,2021-04-23,11:00:58,Streaming,Y,Y,83.0,00:06:48,5.0
4,CA000132,AG007,Sara Ali,2021-04-03,10:58:05,Payment related,Y,Y,113.0,00:05:40,4.0

In [121]:
def assign_agent(call_date):

    # الموظفين المتاحين وقت المكالمة
    available = dim_agents[
        (dim_agents["Hire Date"] <= call_date)
        &
        (
            (dim_agents["Exit Date"].isna())
            |
            (dim_agents["Exit Date"] >= call_date)
        )
    ]

    # اختيار Agent عشوائي
    selected = available.sample(1).iloc[0]

    return selected

In [122]:
def assign_agents(df):

    df = df.copy()

    agent_ids = []
    agent_names = []
    teams = []
    leaders = []

    for call_date in df["Date"]:

        agent = assign_agent(call_date)

        agent_ids.append(agent["AgentID"])
        agent_names.append(agent["Agent"])
        teams.append(agent["Team"])
        leaders.append(agent["Team Leader"])

    df["AgentID"] = agent_ids
    df["Agent"] = agent_names
    df["Team"] = teams
    df["Team Leader"] = leaders

    return df

In [123]:
april = assign_agents(april)

display(
    april[
        [
            "AgentID",
            "Agent",
            "Team",
            "Team Leader",
            "Date"
        ]
    ].head(10)
)

  AgentID          Agent    Team     Team Leader       Date
0   AG001  Ahmed Mohamed  Team A  Mohamed Hassan 2021-04-25
1   AG005  Mostafa Ahmed  Team A  Mohamed Hassan 2021-04-09
2   AG006    Omar Hassan  Team A  Mohamed Hassan 2021-04-13
3   AG001  Ahmed Mohamed  Team A  Mohamed Hassan 2021-04-23
4   AG003   Mahmoud Adel  Team A  Mohamed Hassan 2021-04-03
5   AG006    Omar Hassan  Team A  Mohamed Hassan 2021-04-16
6   AG002    Karim Nabil  Team A  Mohamed Hassan 2021-04-26
7   AG008  Youssef Samir  Team A  Mohamed Hassan 2021-04-18
8   AG004     Menna Wael  Team A  Mohamed Hassan 2021-04-03
9   AG004     Menna Wael  Team A  Mohamed Hassan 2021-04-03

In [124]:
print(april["Agent"].nunique())

print("="*40)

print(
    april["Agent"].value_counts().head(20)
)

8
========================================
Agent
Karim Nabil      251
Menna Wael       236
Mostafa Ahmed    233
Mahmoud Adel     226
Ahmed Mohamed    220
Omar Hassan      213
Sara Ali         213
Youssef Samir    208
Name: count, dtype: int64

In [125]:
from collections import defaultdict

agent_call_counter = defaultdict(int)

In [126]:
def assign_agent(call_date):

    available = dim_agents[
        (dim_agents["Hire Date"] <= call_date)
        &
        (
            (dim_agents["Exit Date"].isna())
            |
            (dim_agents["Exit Date"] >= call_date)
        )
    ].copy()

    # أقل Agent أخذ مكالمات حتى الآن
    min_calls = available["AgentID"].map(
        lambda x: agent_call_counter[x]
    ).min()

    candidates = available[
        available["AgentID"].map(
            lambda x: agent_call_counter[x]
        ) == min_calls
    ]

    selected = candidates.sample(1).iloc[0]

    agent_call_counter[selected["AgentID"]] += 1

    return selected

In [127]:
agent_call_counter.clear()

In [128]:
april = assign_agents(april)

In [129]:
april["Agent"].value_counts().sort_values()

Agent
Mostafa Ahmed    225
Ahmed Mohamed    225
Youssef Samir    225
Sara Ali         225
Karim Nabil      225
Omar Hassan      225
Menna Wael       225
Mahmoud Adel     225
Name: count, dtype: int64

In [130]:
from collections import defaultdict
import random

agent_call_counter = defaultdict(int)

def assign_agent(call_date):

    available = dim_agents[
        (dim_agents["Hire Date"] <= call_date)
        &
        (
            (dim_agents["Exit Date"].isna())
            |
            (dim_agents["Exit Date"] >= call_date)
        )
    ].copy()

    # أقل عدد مكالمات
    min_calls = available["AgentID"].map(
        lambda x: agent_call_counter[x]
    ).min()

    # نسمح بفارق بسيط (من 0 إلى 5 مكالمات)
    candidates = available[
        available["AgentID"].map(
            lambda x: agent_call_counter[x]
        ) <= min_calls + 5
    ]

    selected = candidates.sample(1).iloc[0]

    agent_call_counter[selected["AgentID"]] += 1

    return selected

In [131]:
agent_call_counter.clear()

april = assign_agents(april)

In [132]:
april["Agent"].value_counts().sort_values()

Agent
Ahmed Mohamed    222
Mahmoud Adel     223
Omar Hassan      224
Mostafa Ahmed    225
Sara Ali         225
Menna Wael       226
Youssef Samir    227
Karim Nabil      228
Name: count, dtype: int64

In [133]:
from collections import defaultdict
import random

agent_call_counter = defaultdict(int)

def assign_agent(call_date):

    available = dim_agents[
        (dim_agents["Hire Date"] <= call_date)
        &
        (
            (dim_agents["Exit Date"].isna())
            |
            (dim_agents["Exit Date"] >= call_date)
        )
    ].copy()

    # نحسب Weight عكسي حسب عدد المكالمات الحالية
    weights = []

    for agent_id in available["AgentID"]:

        calls = agent_call_counter[agent_id]

        # كلما زاد عدد المكالمات يقل احتمال الاختيار
        weights.append(1 / (calls + 1))

    selected = random.choices(
        population=available.to_dict("records"),
        weights=weights,
        k=1
    )[0]

    agent_call_counter[selected["AgentID"]] += 1

    return selected

In [134]:
agent_call_counter.clear()

april = assign_agents(april)

In [135]:
april["Agent"].value_counts().sort_values()

Agent
Youssef Samir    210
Karim Nabil      211
Ahmed Mohamed    217
Menna Wael       222
Mostafa Ahmed    231
Omar Hassan      233
Mahmoud Adel     235
Sara Ali         241
Name: count, dtype: int64

In [169]:
# ==========================================
# Generate Full Year 2021 (Q2 + Q3 + Q4)
# ==========================================

# خريطة الشهور
month_mapping = {
    4: 1,
    5: 2,
    6: 3,
    7: 1,
    8: 2,
    9: 3,
    10: 1,
    11: 2,
    12: 3
}

agent_call_counter.clear()

fact_2021 = assign_agents(fact_2021)

full_2021 = [fact_2021.copy()]

for target_month, source_month in month_mapping.items():

    # -----------------------------
    # Template
    # -----------------------------
    month_df = fact_2021[
        fact_2021["Date"].dt.month == source_month
    ].copy()

    # ترتيب عشوائي
    month_df = month_df.sample(
        frac=1,
        random_state=42 + target_month
    ).reset_index(drop=True)

    # -----------------------------
    # تغيير الشهر فقط
    # -----------------------------
    month_df["Date"] = month_df["Date"].apply(
        lambda d: change_date(
            d,
            2021,
            target_month
        )
    )

    # -----------------------------
    # إعادة توزيع الـ Agents
    # -----------------------------
    agent_call_counter.clear()

    month_df = assign_agents(month_df)

    # -----------------------------
    # إضافة للشيت النهائي
    # -----------------------------
    full_2021.append(month_df)

# ==========================================
# دمج السنة كاملة
# ==========================================

fact_2021_full = (
    pd.concat(full_2021, ignore_index=True)
      .sort_values(["Date", "Time"])
      .reset_index(drop=True)
)

# ==========================================
# إعادة ترقيم Call ID
# ==========================================

fact_2021_full["Call Id"] = [
    f"ID{i:05d}"
    for i in range(1, len(fact_2021_full)+1)
]

print(fact_2021_full.shape)

display(fact_2021_full.head())

display(fact_2021_full.tail())

(20000, 13)

,Call Id,AgentID,Agent,Date,Time,Topic,Answered (Y/N),Resolved,Speed of answer in seconds,AvgTalkDuration,Satisfaction rating,Team,Team Leader
0,ID00001,AG004,Menna Wael,2021-01-01,09:12:58,Contract related,Y,Y,109.0,00:02:23,3.0,Team A,Mohamed Hassan
1,ID00002,AG005,Mostafa Ahmed,2021-01-01,09:12:58,Technical Support,Y,N,70.0,00:04:02,3.0,Team A,Mohamed Hassan
2,ID00003,AG004,Menna Wael,2021-01-01,09:47:31,Contract related,Y,Y,10.0,00:02:11,3.0,Team A,Mohamed Hassan
3,ID00004,AG006,Omar Hassan,2021-01-01,09:47:31,Contract related,Y,Y,53.0,00:00:37,2.0,Team A,Mohamed Hassan
4,ID00005,AG008,Youssef Samir,2021-01-01,10:00:29,Payment related,Y,Y,95.0,00:01:00,3.0,Team A,Mohamed Hassan

,Call Id,AgentID,Agent,Date,Time,Topic,Answered (Y/N),Resolved,Speed of answer in seconds,AvgTalkDuration,Satisfaction rating,Team,Team Leader
19995,ID19996,AG001,Ahmed Mohamed,2021-12-28,17:52:48,Streaming,Y,Y,16.0,00:01:23,4.0,Team A,Mohamed Hassan
19996,ID19997,AG004,Menna Wael,2021-12-28,17:57:07,Admin Support,Y,Y,74.0,00:06:08,3.0,Team A,Mohamed Hassan
19997,ID19998,AG008,Youssef Samir,2021-12-28,17:57:07,Contract related,N,N,NaN,NaN,NaN,Team A,Mohamed Hassan
19998,ID19999,AG004,Menna Wael,2021-12-28,17:58:34,Contract related,Y,Y,103.0,00:06:32,5.0,Team A,Mohamed Hassan
19999,ID20000,AG008,Youssef Samir,2021-12-28,17:58:34,Payment related,Y,Y,64.0,00:04:16,3.0,Team A,Mohamed Hassan

In [137]:
fact_2021_full["Date"].dt.month.value_counts().sort_index()

Date
1     1772
2     1616
3     1612
4     1772
5     1616
6     1612
7     1772
8     1616
9     1612
10    1772
11    1616
12    1612
Name: count, dtype: int64

In [138]:
fact_2021_full["Agent"].nunique()

8

In [139]:
fact_2021_full["Team"].value_counts()

Team
Team A    15000
Name: count, dtype: int64

In [140]:
print("=" * 60)
print("TEST 1 : Dataset Shape")
print("=" * 60)

print(f"Rows : {len(fact_2021_full):,}")
print(f"Columns : {fact_2021_full.shape[1]}")

print("\n✅ Passed")

============================================================
TEST 1 : Dataset Shape
============================================================
Rows : 20,000
Columns : 13

✅ Passed

In [141]:
print("=" * 60)
print("TEST 2 : Months")
print("=" * 60)

months = sorted(fact_2021_full["Date"].dt.month.unique())

print(months)

if months == list(range(1,13)):
    print("\n✅ All Months Exist")
else:
    print("\n❌ Missing Months")

============================================================
TEST 2 : Months
============================================================
[np.int32(1), np.int32(2), np.int32(3), np.int32(4), np.int32(5), np.int32(6), np.int32(7), np.int32(8), np.int32(9), np.int32(10), np.int32(11), np.int32(12)]

✅ All Months Exist

In [142]:
print("=" * 60)
print("TEST 3 : Calls Per Month")
print("=" * 60)

display(
    fact_2021_full["Date"]
    .dt.month
    .value_counts()
    .sort_index()
)

============================================================
TEST 3 : Calls Per Month
============================================================

Date
1     1772
2     1616
3     1612
4     1772
5     1616
6     1612
7     1772
8     1616
9     1612
10    1772
11    1616
12    1612
Name: count, dtype: int64

In [143]:
print("=" * 60)
print("TEST 4 : Duplicate Call IDs")
print("=" * 60)

duplicates = fact_2021_full["Call Id"].duplicated().sum()

print("Duplicate IDs :", duplicates)

if duplicates == 0:
    print("\n✅ Passed")
else:
    print("\n❌ Duplicate IDs Found")

============================================================
TEST 4 : Duplicate Call IDs
============================================================
Duplicate IDs : 0

✅ Passed

In [144]:
print("=" * 60)
print("TEST 5 : Agents")
print("=" * 60)

print("Unique Agents :", fact_2021_full["Agent"].nunique())

display(
    fact_2021_full["Agent"]
    .value_counts()
)

============================================================
TEST 5 : Agents
============================================================
Unique Agents : 8

Agent
Sara Ali         2538
Omar Hassan      2522
Menna Wael       2510
Ahmed Mohamed    2508
Youssef Samir    2507
Mostafa Ahmed    2496
Mahmoud Adel     2476
Karim Nabil      2443
Name: count, dtype: int64

In [145]:
print("=" * 60)
print("TEST 6 : Agent Mapping")
print("=" * 60)

mapping = (
    fact_2021_full
    .groupby("Agent")["AgentID"]
    .nunique()
)

problem = mapping[mapping > 1]

if len(problem)==0:
    print("✅ Passed")
else:
    print(problem)

============================================================
TEST 6 : Agent Mapping
============================================================
✅ Passed

In [146]:
print("=" * 60)
print("TEST 7 : Team Mapping")
print("=" * 60)

mapping = (
    fact_2021_full
    .groupby("Agent")["Team"]
    .nunique()
)

problem = mapping[mapping > 1]

if len(problem)==0:
    print("✅ Passed")
else:
    print(problem)

============================================================
TEST 7 : Team Mapping
============================================================
✅ Passed

In [164]:
print("=" * 60)
print("TEST 8 : Team Leader Mapping")
print("=" * 60)

mapping = (
    fact_2021_full
    .groupby("Team")["Team Leader"]
    .nunique()
)

problem = mapping[mapping > 1]

if len(problem)==0:
    print("✅ Passed")
else:
    print(problem)

============================================================
TEST 8 : Team Leader Mapping
============================================================
✅ Passed

In [172]:
wrong = validation_df[
    validation_df["Date"] < validation_df["Hire Date"]
]

print("Wrong Records:", len(wrong))

if len(wrong) > 0:
    display(wrong.head())

Wrong Records: 0

In [173]:
wrong = validation_df[
    (validation_df["Exit Date"].notna()) &
    (validation_df["Date"] > validation_df["Exit Date"])
]

print("Wrong Records:", len(wrong))

if len(wrong) > 0:
    display(wrong.head())

Wrong Records: 0

agent_call_counter.clear()

fact_2021 = assign_agents(fact_2021)

full_2021 = [fact_2021.copy()]

In [170]:
print("=" * 60)
print("TEST 11 : Missing Values")
print("=" * 60)

display(
    fact_2021_full
    .isna()
    .sum()
)

============================================================
TEST 11 : Missing Values
============================================================

Call Id                          0
AgentID                          0
Agent                            0
Date                             0
Time                             0
Topic                            0
Answered (Y/N)                   0
Resolved                         0
Speed of answer in seconds    3784
AvgTalkDuration               3784
Satisfaction rating           3784
Team                             0
Team Leader                      0
dtype: int64

In [151]:
print("=" * 60)
print("TEST 12 : Hour Distribution")
print("=" * 60)

hours = pd.to_datetime(
    fact_2021_full["Time"].astype(str)
).dt.hour

display(
    hours.value_counts()
    .sort_index()
)

============================================================
TEST 12 : Hour Distribution
============================================================

C:\Users\Hp(ZG8)\AppData\Local\Temp\ipykernel_32688\1758727137.py:5: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  hours = pd.to_datetime(

Time
9     2188
10    2116
11    2360
12    2188
13    2376
14    1996
15    2124
16    2264
17    2332
18      56
Name: count, dtype: int64

In [152]:
print("=" * 60)
print("TEST 13 : Topics")
print("=" * 60)

display(
    fact_2021_full["Topic"]
    .value_counts()
)

============================================================
TEST 13 : Topics
============================================================

Topic
Streaming            4088
Technical Support    4076
Payment related      4028
Contract related     3904
Admin Support        3904
Name: count, dtype: int64

In [153]:
print("=" * 60)
print("TEST 14 : Resolution Rate")
print("=" * 60)

display(
    fact_2021_full["Resolved"]
    .value_counts(normalize=True)*100
)

============================================================
TEST 14 : Resolution Rate
============================================================

Resolved
Y    72.92
N    27.08
Name: proportion, dtype: float64

In [154]:
print("=" * 60)
print("TEST 15 : Answer Rate")
print("=" * 60)

display(
    fact_2021_full["Answered (Y/N)"]
    .value_counts(normalize=True)*100
)

============================================================
TEST 15 : Answer Rate
============================================================

Answered (Y/N)
Y    81.08
N    18.92
Name: proportion, dtype: float64

In [155]:
print("=" * 60)
print("TEST 16 : Satisfaction")
print("=" * 60)

display(
    fact_2021_full["Satisfaction rating"]
    .value_counts()
    .sort_index()
)

============================================================
TEST 16 : Satisfaction
============================================================

Satisfaction rating
1.0    1668
2.0    1584
3.0    4872
4.0    4720
5.0    3372
Name: count, dtype: int64

In [156]:
print("=" * 60)
print("TEST 17 : Speed of Answer")
print("=" * 60)

display(
    fact_2021_full["Speed of answer in seconds"]
    .describe()
)

============================================================
TEST 17 : Speed of Answer
============================================================

count    16216.000000
mean        67.520720
std         33.589765
min         10.000000
25%         39.000000
50%         68.000000
75%         97.000000
max        125.000000
Name: Speed of answer in seconds, dtype: float64

In [157]:
print("=" * 60)
print("TEST 18 : AvgTalkDuration")
print("=" * 60)

display(
    fact_2021_full["AvgTalkDuration"]
    .describe()
)

============================================================
TEST 18 : AvgTalkDuration
============================================================

count        16216
unique         391
top       00:04:43
freq            88
Name: AvgTalkDuration, dtype: object

In [158]:
print("=" * 60)
print("TEST 19 : Calls Per Day")
print("=" * 60)

display(
    fact_2021_full
    .groupby("Date")
    .size()
    .describe()
)

============================================================
TEST 19 : Calls Per Day
============================================================

count    342.000000
mean      58.479532
std       22.355391
min       25.000000
25%       50.000000
50%       56.000000
75%       62.000000
max      254.000000
dtype: float64

In [159]:
print("="*60)
print("VALIDATION SUMMARY")
print("="*60)

print(f"""
Dataset : PASS

Rows : {len(fact_2021_full):,}

Months : {fact_2021_full['Date'].dt.month.nunique()}

Agents : {fact_2021_full['Agent'].nunique()}

Teams : {fact_2021_full['Team'].nunique()}

Call IDs :
{"PASS" if fact_2021_full["Call Id"].duplicated().sum()==0 else "FAIL"}

Missing Values :
{fact_2021_full.isna().sum().sum()}

""")

============================================================
VALIDATION SUMMARY
============================================================

Dataset : PASS

Rows : 20,000

Months : 12

Agents : 8

Teams : 1

Call IDs :
PASS

Missing Values :
21352

In [171]:
validation_df = fact_2021_full.merge(
    dim_agents[
        ["AgentID", "Hire Date", "Exit Date"]
    ],
    on="AgentID",
    how="left"
)

In [174]:
TARGET_CALLS_2022 = 25000

In [175]:
# ==========================================
# Generate 2022 Dataset
# ==========================================

# استخدام 2021 كـ Template
template_2022 = fact_2021_full.copy()

# أخذ Sample بالحجم المطلوب
fact_2022 = (
    template_2022
    .sample(
        n=TARGET_CALLS_2022,
        replace=True,
        random_state=2022
    )
    .reset_index(drop=True)
)

# تغيير السنة فقط
fact_2022["Date"] = fact_2022["Date"].apply(
    lambda d: d.replace(year=2022)
)

# ترتيب حسب التاريخ والوقت
fact_2022 = (
    fact_2022
    .sort_values(["Date", "Time"])
    .reset_index(drop=True)
)

In [176]:
# ==========================================
# Assign Active Agents (2022)
# ==========================================

agent_call_counter.clear()

fact_2022 = assign_agents(fact_2022)

In [177]:
fact_2022["Call Id"] = [
    f"2022-{i:06d}"
    for i in range(1, len(fact_2022) + 1)
]

In [178]:
print("=" * 60)

print("Rows :", len(fact_2022))

print("Agents :", fact_2022["Agent"].nunique())

print("Months :", fact_2022["Date"].dt.month.nunique())

print("Teams :", fact_2022["Team"].nunique())

print("=" * 60)

display(fact_2022.head())

display(fact_2022.tail())

============================================================
Rows : 25000
Agents : 45
Months : 12
Teams : 5
============================================================

,Call Id,AgentID,Agent,Date,Time,Topic,Answered (Y/N),Resolved,Speed of answer in seconds,AvgTalkDuration,Satisfaction rating,Team,Team Leader
0,2022-000001,AG002,Karim Nabil,2022-01-01,09:12:58,Contract related,Y,Y,109.0,00:02:23,3.0,Team A,Mohamed Hassan
1,2022-000002,AG008,Youssef Samir,2022-01-01,09:12:58,Contract related,Y,Y,109.0,00:02:23,3.0,Team A,Mohamed Hassan
2,2022-000003,AG006,Omar Hassan,2022-01-01,09:47:31,Contract related,Y,Y,53.0,00:00:37,2.0,Team A,Mohamed Hassan
3,2022-000004,AG001,Ahmed Mohamed,2022-01-01,10:00:29,Technical Support,N,N,NaN,NaN,NaN,Team A,Mohamed Hassan
4,2022-000005,AG004,Menna Wael,2022-01-01,10:00:29,Technical Support,N,N,NaN,NaN,NaN,Team A,Mohamed Hassan

,Call Id,AgentID,Agent,Date,Time,Topic,Answered (Y/N),Resolved,Speed of answer in seconds,AvgTalkDuration,Satisfaction rating,Team,Team Leader
24995,2022-024996,AG036,Habiba Hamdy,2022-12-28,17:52:48,Contract related,Y,Y,32.0,00:00:47,3.0,Team D,Sara Ahmed
24996,2022-024997,AG045,Hazem Hamdy,2022-12-28,17:57:07,Admin Support,Y,Y,74.0,00:06:08,3.0,Team E,Mahmoud Adel
24997,2022-024998,AG045,Hazem Hamdy,2022-12-28,17:57:07,Contract related,N,N,NaN,NaN,NaN,Team E,Mahmoud Adel
24998,2022-024999,AG018,Hassan Abdelrahman,2022-12-28,17:58:34,Contract related,Y,Y,103.0,00:06:32,5.0,Team B,Ahmed Mostafa
24999,2022-025000,AG031,Mazen Khaled,2022-12-28,17:58:34,Contract related,Y,Y,103.0,00:06:32,5.0,Team D,Sara Ahmed

In [179]:
print("Calls Per Agent")

display(
    fact_2022["Agent"]
    .value_counts()
    .sort_values()
)

Calls Per Agent

Agent
Mazen Khaled          115
Rami Mostafa          166
Habiba Hamdy          176
Ibrahim Fathy         191
Nour Shaban           201
Amr Khaled            220
Rami Tarek            226
Islam Mahmoud         229
Karim Nabil           233
Eslam Adel            253
Ahmed Reda            332
Mahmoud Mohamed       439
Hazem Hamdy           458
Ahmed Mohamed         498
Hossam Gamal          550
Hassan Ibrahim        562
Bishoy Salem          564
Eslam Ashraf          564
Bishoy Samir          585
Salma Ahmed           586
Hazem Mostafa         598
Wael Hamdy            608
Nour Nabil            609
Aya Tarek             613
Hazem Sherif          617
Ahmed Hamdy           628
Youssef Tarek         630
Menna Farouk          649
Rana Farouk           650
Esraa Abdelrahman     678
Yara Ibrahim          683
Youssef Hamdy         685
Eslam Mahmoud         701
Farah Mostafa         738
Hassan Abdelrahman    757
Ibrahim Fouad         763
Mohamed Fathy         763
Mahmoud Adel          785
Mohamed Hassan        789
Youssef Samir         805
Mostafa Ahmed         806
Laila Tarek           816
Menna Wael            820
Omar Hassan           823
Sara Ali              838
Name: count, dtype: int64

In [180]:
TARGET_CALLS_2022 = 25000
TARGET_CALLS_2023 = 40000

In [181]:
fact_2022.groupby(
    fact_2022["Date"].dt.month
)["Agent"].nunique()

Date
1     12
2     14
3     16
4     23
5     27
6     29
7     31
8     32
9     33
10    34
11    40
12    43
Name: Agent, dtype: int64

In [182]:
validation_2022 = fact_2022.merge(
    dim_agents[
        ["AgentID","Hire Date","Exit Date"]
    ],
    on="AgentID",
    how="left"
)

wrong = validation_2022[
    (validation_2022["Exit Date"].notna())
    &
    (validation_2022["Date"] > validation_2022["Exit Date"])
]

print(len(wrong))

0

In [183]:
wrong = validation_2022[
    validation_2022["Date"] <
    validation_2022["Hire Date"]
]

print(len(wrong))

0

In [184]:
fact_2022["Agent"].value_counts().describe()

count     45.000000
mean     555.555556
std      220.716453
min      115.000000
25%      439.000000
50%      609.000000
75%      738.000000
max      838.000000
Name: count, dtype: float64

In [185]:
fact_2023 = generate_year(
    year=2023,
    target_calls=TARGET_CALLS_2023
)

NameError: name 'generate_year' is not defined

In [186]:
def generate_year(year, target_calls):

    # توزيع المكالمات على الشهور
    month_targets = monthly_targets(target_calls)

    all_months = []

    for month in range(1, 13):

        # Template من نفس الشهر في 2021
        template = fact_2021_full[
            fact_2021_full["Date"].dt.month == month
        ].copy()

        # عدد المكالمات المطلوبة
        n_calls = month_targets.loc[month]

        # Sampling
        month_df = (
            template
            .sample(
                n=n_calls,
                replace=True,
                random_state=year * 100 + month
            )
            .reset_index(drop=True)
        )

        # تغيير السنة
        month_df["Date"] = month_df["Date"].apply(
            lambda d: d.replace(year=year)
        )

        # إعادة توزيع الـ Agents
        agent_call_counter.clear()

        month_df = assign_agents(month_df)

        all_months.append(month_df)

    # دمج السنة
    year_df = (
        pd.concat(all_months, ignore_index=True)
        .sort_values(["Date", "Time"])
        .reset_index(drop=True)
    )

    # Call ID
    year_df["Call Id"] = [
        f"{year}-{i:06d}"
        for i in range(1, len(year_df) + 1)
    ]

    return year_df

In [187]:
TARGET_CALLS_2023 = 40000

In [188]:
fact_2023 = generate_year(
    year=2023,
    target_calls=TARGET_CALLS_2023
)

NameError: name 'monthly_targets' is not defined

In [189]:
globals().keys()

dict_keys(['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__builtin__', '__builtins__', '_ih', '_oh', '_dh', 'In', 'Out', 'get_ipython', 'exit', 'quit', 'open', '_', '__', '___', '__vsc_ipynb_file__', '__DW_SCOPE__', '_i', '_ii', '_iii', '_i1', 'pd', '_i2', 'random', 'string', 'Faker', '_i3', 'df', '_3', '_i4', '_4', '_i5', 'agents', '_5', '_i6', 'new_agents', '_6', '_i7', 'agent_ids', 'cols', 'call_index', '_7', '_i8', '_8', '_i9', 'dim_agents', '_9', '_i10', '_10', '_i11', '_11', '_i12', 'first_names', 'last_names', '_i13', 'generate_name', '_i14', '_i15', 'male_first_names', '_i16', 'female_first_names', '_i17', '_i18', '_i19', 'i', 'gender', '_i20', 'current_agents', 'teams', 'team_leaders', '_i21', 'create_agent', '_21', '_i22', 'hire', '_22', '_i23', 'gender_map', '_23', '_i24', '_24', '_i25', '_i26', '_i27', '_i28', '_i29', 'leaders', '_i30', 'mask', 'idx', 'index', 'team', '_i31', '_31', '_i32', '_i33', '_i34', '_i35', 'team_names', 'team_index', '_i36', '_36', '_i37', 'agents_2021', 'resigned_2021', '_37', '_i38', 'agents_2022', 'resigned_2022', '_38', '_i39', '_i40', '_40', '_i41', 'generate_call_id', '_i42', '_i43', '_43', '_i44', '_44', '_i45', 'fact_2021', '_45', '_i46', '_46', '_i47', '_47', '_i48', '_i49', '_i50', '_i51', '_51', '_i52', '_i53', '_i54', '_i55', '_i56', '_i57', '_i58', '_58', '_i59', '_59', '_i60', '_60', '_i61', '_61', '_i62', '_62', '_i63', '_63', '_i64', '_i65', '_65', '_i66', '_66', '_i67', 'end_2021', '_i68', 'end_2022', '_i69', '_i70', '_i71', '_i72', 'get_active_agents', '_i73', '_i74', '_i75', '_i76', 'change_year', '_i77', '_i78', 'get_available_agents', '_i79', '_79', '_i80', '_i81', 'active_agents_in_month', '_i82', 'month', '_i83', 'calculate_weight', '_i84', 'choose_agent', '_i85', 'agent', '_i86', 'get_month_template', '_i87', 'calls', '_i88', 'monthly_active_agents', '_88', '_i89', 'active_2022', '_89', '_i90', 'CALLS_PER_AGENT', '_90', '_i91', 'calculate_monthly_calls', '_91', '_i92', 'calls_2022', '_92', '_i93', '_93', '_i94', 'active_2021', 'calls_2021', '_94', '_i95', '_95', '_i96', '_96', '_i97', '_97', '_i98', '_98', '_i99', '_99', '_i100', '_100', '_i101', 'monthly_distribution', '_101', '_i102', 'TARGET_CALLS_2022', '_102', '_i103', 'TARGET_CALLS_2023', '_103', '_i104', '_104', '_i105', '_105', '_i106', 'jan', '_106', '_i107', 'expand_month', '_i108', 'jan_2022', '_108', '_i109', 'update_year', '_i110', '_110', '_i111', '_111', '_i112', '_112', '_i113', 'change_date', '_113', '_i114', '_i115', 'get_template_month', '_i116', 'm', '_i117', 'simulate_month', '_i118', 'april', '_118', '_i119', '_i120', '_120', '_i121', 'assign_agent', '_i122', 'assign_agents', '_i123', '_123', '_i124', '_i125', 'defaultdict', 'agent_call_counter', '_i126', '_i127', '_i128', '_i129', '_129', '_i130', '_i131', '_i132', '_132', '_i133', '_i134', '_i135', '_135', '_i136', 'month_mapping', 'full_2021', 'target_month', 'source_month', 'month_df', 'fact_2021_full', '_136', '_i137', '_137', '_i138', '_138', '_i139', '_139', '_i140', '_i141', 'months', '_i142', '_142', '_i143', 'duplicates', '_i144', '_144', '_i145', 'mapping', 'problem', '_i146', '_i147', '_i148', '_i149', '_i150', '_150', '_i151', 'hours', '_151', '_i152', '_152', '_i153', '_153', '_i154', '_154', '_i155', '_155', '_i156', '_156', '_i157', '_157', '_i158', '_158', '_i159', '_i160', '_160', '_i161', '_161', '_i162', '_162', '_i163', '_i164', '_i165', '_165', '_i166', '_i167', '_i168', '_168', '_i169', '_169', '_i170', '_170', '_i171', 'validation_df', '_i172', 'wrong', '_i173', '_i174', '_i175', 'template_2022', 'fact_2022', '_i176', '_i177', '_i178', '_178', '_i179', '_179', '_i180', '_i181', '_181', '_i182', 'validation_2022', '_i183', '_i184', '_184', '_i185', '_i186', 'generate_year', '_i187', '_i188', '_i189'])

In [190]:
def monthly_targets(total_calls):
    """
    توزيع عدد المكالمات على الشهور
    بناءً على توزيع 2021
    """

    monthly = (
        fact_2021_full["Date"]
        .dt.month
        .value_counts(normalize=True)
        .sort_index()
    )

    monthly = (monthly * total_calls).round().astype(int)

    # تصحيح فرق التقريب
    diff = total_calls - monthly.sum()
    monthly.iloc[-1] += diff

    return monthly

In [191]:
monthly_targets(TARGET_CALLS_2023)

Date
1     3544
2     3232
3     3224
4     3544
5     3232
6     3224
7     3544
8     3232
9     3224
10    3544
11    3232
12    3224
Name: proportion, dtype: int64

In [192]:
fact_2023 = generate_year(
    year=2023,
    target_calls=TARGET_CALLS_2023
)

In [193]:
print("=" * 60)

print("Rows :", len(fact_2023))
print("Agents :", fact_2023["Agent"].nunique())
print("Months :", fact_2023["Date"].dt.month.nunique())
print("Teams :", fact_2023["Team"].nunique())

print("=" * 60)

display(fact_2023.head())

display(fact_2023.tail())

============================================================
Rows : 40000
Agents : 96
Months : 12
Teams : 10
============================================================

,Call Id,AgentID,Agent,Date,Time,Topic,Answered (Y/N),Resolved,Speed of answer in seconds,AvgTalkDuration,Satisfaction rating,Team,Team Leader
0,2023-000001,AG005,Mostafa Ahmed,2023-01-01,09:12:58,Technical Support,Y,N,70.0,00:04:02,3.0,Team A,Mohamed Hassan
1,2023-000002,AG011,Mahmoud Mohamed,2023-01-01,09:12:58,Contract related,Y,Y,109.0,00:02:23,3.0,Team B,Ahmed Mostafa
2,2023-000003,AG022,Bishoy Samir,2023-01-01,09:12:58,Contract related,Y,Y,109.0,00:02:23,3.0,Team C,Omar Ali
3,2023-000004,AG045,Hazem Hamdy,2023-01-01,09:12:58,Contract related,Y,Y,109.0,00:02:23,3.0,Team E,Mahmoud Adel
4,2023-000005,AG035,Ahmed Reda,2023-01-01,10:00:29,Payment related,Y,Y,95.0,00:01:00,3.0,Team D,Sara Ahmed

,Call Id,AgentID,Agent,Date,Time,Topic,Answered (Y/N),Resolved,Speed of answer in seconds,AvgTalkDuration,Satisfaction rating,Team,Team Leader
39995,2023-039996,AG043,Salma Ahmed,2023-12-28,17:39:50,Contract related,N,N,NaN,NaN,NaN,Team E,Mahmoud Adel
39996,2023-039997,AG021,Aya Tarek,2023-12-28,17:52:48,Contract related,Y,Y,32.0,00:00:47,3.0,Team C,Omar Ali
39997,2023-039998,AG068,Mostafa Salem,2023-12-28,17:57:07,Admin Support,Y,Y,74.0,00:06:08,3.0,Team G,Youssef Khaled
39998,2023-039999,AG045,Hazem Hamdy,2023-12-28,17:58:34,Payment related,Y,Y,64.0,00:04:16,3.0,Team E,Mahmoud Adel
39999,2023-040000,AG073,Mahmoud Youssef,2023-12-28,17:58:34,Payment related,Y,Y,64.0,00:04:16,3.0,Team H,Nada Ashraf

In [194]:
fact_2023["Agent"].value_counts().describe()

count      96.000000
mean      416.666667
std       196.885736
min        23.000000
25%       279.250000
50%       454.000000
75%       573.250000
max      1147.000000
Name: count, dtype: float64

In [195]:
validation_2023 = fact_2023.merge(
    dim_agents[
        ["AgentID", "Hire Date", "Exit Date"]
    ],
    on="AgentID",
    how="left"
)

print("Calls before Hire Date:",
      len(validation_2023[
          validation_2023["Date"] < validation_2023["Hire Date"]
      ]))

print("Calls after Exit Date:",
      len(validation_2023[
          (validation_2023["Exit Date"].notna()) &
          (validation_2023["Date"] > validation_2023["Exit Date"])
      ]))

Calls before Hire Date: 0
Calls after Exit Date: 0

In [196]:
fact_calls = pd.concat(
    [
        fact_2021_full,
        fact_2022,
        fact_2023
    ],
    ignore_index=True
)

fact_calls = fact_calls.sort_values(
    ["Date", "Time"]
).reset_index(drop=True)

print(fact_calls.shape)

display(fact_calls.head())

display(fact_calls.tail())

(85000, 13)

,Call Id,AgentID,Agent,Date,Time,Topic,Answered (Y/N),Resolved,Speed of answer in seconds,AvgTalkDuration,Satisfaction rating,Team,Team Leader
0,ID00001,AG004,Menna Wael,2021-01-01,09:12:58,Contract related,Y,Y,109.0,00:02:23,3.0,Team A,Mohamed Hassan
1,ID00002,AG005,Mostafa Ahmed,2021-01-01,09:12:58,Technical Support,Y,N,70.0,00:04:02,3.0,Team A,Mohamed Hassan
2,ID00003,AG004,Menna Wael,2021-01-01,09:47:31,Contract related,Y,Y,10.0,00:02:11,3.0,Team A,Mohamed Hassan
3,ID00004,AG006,Omar Hassan,2021-01-01,09:47:31,Contract related,Y,Y,53.0,00:00:37,2.0,Team A,Mohamed Hassan
4,ID00005,AG008,Youssef Samir,2021-01-01,10:00:29,Payment related,Y,Y,95.0,00:01:00,3.0,Team A,Mohamed Hassan

,Call Id,AgentID,Agent,Date,Time,Topic,Answered (Y/N),Resolved,Speed of answer in seconds,AvgTalkDuration,Satisfaction rating,Team,Team Leader
84995,2023-039996,AG043,Salma Ahmed,2023-12-28,17:39:50,Contract related,N,N,NaN,NaN,NaN,Team E,Mahmoud Adel
84996,2023-039997,AG021,Aya Tarek,2023-12-28,17:52:48,Contract related,Y,Y,32.0,00:00:47,3.0,Team C,Omar Ali
84997,2023-039998,AG068,Mostafa Salem,2023-12-28,17:57:07,Admin Support,Y,Y,74.0,00:06:08,3.0,Team G,Youssef Khaled
84998,2023-039999,AG045,Hazem Hamdy,2023-12-28,17:58:34,Payment related,Y,Y,64.0,00:04:16,3.0,Team E,Mahmoud Adel
84999,2023-040000,AG073,Mahmoud Youssef,2023-12-28,17:58:34,Payment related,Y,Y,64.0,00:04:16,3.0,Team H,Nada Ashraf

In [197]:
fact_calls.to_csv(
    "Fact_Calls.csv",
    index=False
)

dim_agents.to_csv(
    "Dim_Agents.csv",
    index=False
)

print("Files Saved Successfully ✅")

Files Saved Successfully ✅

In [198]:
import numpy as np

departments = [
    "Internet",
    "Mobile",
    "Landline"
]

department_weights = [
    0.45,
    0.35,
    0.20
]

In [199]:
def add_department(df):

    df = df.copy()

    df["Department"] = np.random.choice(
        departments,
        size=len(df),
        p=department_weights
    )

    return df

In [200]:
fact_2021_full = add_department(fact_2021_full)

fact_2022 = add_department(fact_2022)

fact_2023 = add_department(fact_2023)

In [201]:
for year_name, data in {
    "2021": fact_2021_full,
    "2022": fact_2022,
    "2023": fact_2023
}.items():

    print("="*60)
    print(year_name)
    print("="*60)

    print(
        data["Department"]
        .value_counts(normalize=True)
        .mul(100)
        .round(2)
    )

============================================================
2021
============================================================
Department
Internet    44.89
Mobile      35.30
Landline    19.80
Name: proportion, dtype: float64
============================================================
2022
============================================================
Department
Internet    44.92
Mobile      35.12
Landline    19.96
Name: proportion, dtype: float64
============================================================
2023
============================================================
Department
Internet    45.19
Mobile      34.88
Landline    19.93
Name: proportion, dtype: float64

In [202]:
def get_shift(call_time):

    # تحويل الوقت إلى ساعة
    hour = pd.to_datetime(str(call_time)).hour

    if 8 <= hour < 16:
        return "Morning"

    elif 16 <= hour < 24:
        return "Evening"

    else:
        return "Night"

In [203]:
def add_shift(df):

    df = df.copy()

    df["Shift"] = df["Time"].apply(get_shift)

    return df

In [204]:
fact_2021_full = add_shift(fact_2021_full)

fact_2022 = add_shift(fact_2022)

fact_2023 = add_shift(fact_2023)

In [205]:
for year_name, data in {
    "2021": fact_2021_full,
    "2022": fact_2022,
    "2023": fact_2023
}.items():

    print("=" * 50)
    print(year_name)
    print("=" * 50)

    print(data["Shift"].value_counts())

==================================================
2021
==================================================
Shift
Morning    15348
Evening     4652
Name: count, dtype: int64
==================================================
2022
==================================================
Shift
Morning    19265
Evening     5735
Name: count, dtype: int64
==================================================
2023
==================================================
Shift
Morning    30610
Evening     9390
Name: count, dtype: int64

In [206]:
display(
    fact_2023[
        ["Time", "Shift"]
    ].sample(20)
)

           Time    Shift
940    12:33:07  Morning
35328  11:12:29  Morning
16263  15:28:48  Morning
12427  16:01:55  Evening
23674  10:35:02  Morning
8047   10:01:55  Morning
36360  12:05:46  Morning
29866  14:42:43  Morning
11744  13:36:29  Morning
13434  16:13:26  Evening
26734  13:40:48  Morning
11745  13:36:29  Morning
12643  15:48:58  Morning
15708  13:29:17  Morning
18678  17:12:29  Evening
3854   13:32:10  Morning
27911  17:05:17  Evening
4986   09:41:46  Morning
38843  11:12:29  Morning
38987  12:53:17  Morning

In [207]:
import numpy as np

def generate_queue_time(answered):

    if answered == "Y":
        # معظم المكالمات المجابة
        return np.random.randint(5, 61)

    else:
        # العميل انتظر كثيرًا ثم أغلق
        return np.random.randint(60, 301)

In [208]:
def add_queue_time(df):

    df = df.copy()

    df["Queue Time (Sec)"] = df["Answered (Y/N)"].apply(
        generate_queue_time
    )

    return df

In [209]:
fact_2021_full = add_queue_time(fact_2021_full)

fact_2022 = add_queue_time(fact_2022)

fact_2023 = add_queue_time(fact_2023)

In [210]:
for year_name, data in {
    "2021": fact_2021_full,
    "2022": fact_2022,
    "2023": fact_2023
}.items():

    print("=" * 50)
    print(year_name)
    print("=" * 50)

    print(data["Queue Time (Sec)"].describe())

==================================================
2021
==================================================
count    20000.000000
mean        60.593050
std         66.747501
min          5.000000
25%         22.000000
50%         39.000000
75%         56.000000
max        300.000000
Name: Queue Time (Sec), dtype: float64
==================================================
2022
==================================================
count    25000.000000
mean        60.641760
std         66.886841
min          5.000000
25%         22.000000
50%         39.000000
75%         56.000000
max        300.000000
Name: Queue Time (Sec), dtype: float64
==================================================
2023
==================================================
count    40000.000000
mean        60.308875
std         66.664888
min          5.000000
25%         22.000000
50%         39.000000
75%         56.000000
max        300.000000
Name: Queue Time (Sec), dtype: float64

In [211]:
fact_2023.groupby("Answered (Y/N)")["Queue Time (Sec)"].describe()

,count,mean,std,min,25%,50%,75%,max
Answered (Y/N),,,,,,,,
N,7560.0,179.507672,69.729227,60.0,119.0,180.0,240.0,300.0
Y,32440.0,32.530117,16.247189,5.0,18.0,33.0,47.0,60.0

In [212]:
fact_2023["AvgTalkDuration"].head()

0    00:04:02
1    00:02:23
2    00:02:23
3    00:02:23
4    00:01:00
Name: AvgTalkDuration, dtype: object

In [213]:
fact_2023["AvgTalkDuration"].sample(5)

376      00:04:17
21447         NaN
30006    00:00:37
15484    00:06:25
11225    00:00:53
Name: AvgTalkDuration, dtype: object

In [214]:
import numpy as np

def generate_hold_time(answered):

    if answered == "N":
        return 0

    # 70% من المكالمات بدون Hold
    if np.random.rand() < 0.70:
        return 0

    # 30% فيها Hold
    return np.random.randint(5, 91)

In [215]:
def add_hold_time(df):

    df = df.copy()

    df["Hold Time (Sec)"] = df["Answered (Y/N)"].apply(
        generate_hold_time
    )

    return df

In [216]:
fact_2021_full = add_hold_time(fact_2021_full)

fact_2022 = add_hold_time(fact_2022)

fact_2023 = add_hold_time(fact_2023)

In [217]:
for year_name, data in {
    "2021": fact_2021_full,
    "2022": fact_2022,
    "2023": fact_2023
}.items():

    print("=" * 50)
    print(year_name)
    print("=" * 50)

    print(data["Hold Time (Sec)"].describe())

    print("\nHold Distribution:")

    print(
        data["Hold Time (Sec)"]
        .gt(0)
        .value_counts(normalize=True)
        .mul(100)
        .round(2)
    )

    print()

==================================================
2021
==================================================
count    20000.000000
mean        11.367350
std         23.619494
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max         90.000000
Name: Hold Time (Sec), dtype: float64

Hold Distribution:
Hold Time (Sec)
False    75.94
True     24.06
Name: proportion, dtype: float64

==================================================
2022
==================================================
count    25000.000000
mean        11.441040
std         23.760143
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max         90.000000
Name: Hold Time (Sec), dtype: float64

Hold Distribution:
Hold Time (Sec)
False    76.03
True     23.97
Name: proportion, dtype: float64

==================================================
2023
==================================================
count    40000.000000
mean        11.518075
std         23.757892
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max         90.000000
Name: Hold Time (Sec), dtype: float64

Hold Distribution:
Hold Time (Sec)
False    75.7
True     24.3
Name: proportion, dtype: float64

In [218]:
import numpy as np

def generate_acw(answered):

    # لو المكالمة غير مجابة
    if answered == "N":
        return 0

    # توزيع طبيعي بمتوسط 30 ثانية
    acw = np.random.normal(loc=30, scale=10)

    # منع القيم الشاذة
    acw = max(10, min(90, round(acw)))

    return acw

In [219]:
def add_acw(df):

    df = df.copy()

    df["ACW (Sec)"] = df["Answered (Y/N)"].apply(generate_acw)

    return df

In [220]:
fact_2021_full = add_acw(fact_2021_full)

fact_2022 = add_acw(fact_2022)

fact_2023 = add_acw(fact_2023)

In [221]:
for year_name, data in {
    "2021": fact_2021_full,
    "2022": fact_2022,
    "2023": fact_2023
}.items():

    print("=" * 50)
    print(year_name)
    print("=" * 50)

    print(data["ACW (Sec)"].describe())

    print()

    print(
        data.groupby("Answered (Y/N)")["ACW (Sec)"]
        .describe()
    )

    print("\n")

==================================================
2021
==================================================
count    20000.000000
mean        24.456700
std         14.800111
min          0.000000
25%         16.000000
50%         27.000000
75%         35.000000
max         68.000000
Name: ACW (Sec), dtype: float64

                  count       mean       std   min   25%   50%   75%   max
Answered (Y/N)
N                3784.0   0.000000  0.000000   0.0   0.0   0.0   0.0   0.0
Y               16216.0  30.163666  9.899824  10.0  23.0  30.0  37.0  68.0


==================================================
2022
==================================================
count    25000.000000
mean        24.304400
std         14.775899
min          0.000000
25%         15.000000
50%         27.000000
75%         35.000000
max         70.000000
Name: ACW (Sec), dtype: float64

                  count       mean       std   min   25%   50%   75%   max
Answered (Y/N)
N                4792.0   0.000000  0.000000   0.0   0.0   0.0   0.0   0.0
Y               20208.0  30.067795  9.838768  10.0  23.0  30.0  37.0  70.0


==================================================
2023
==================================================
count    40000.000000
mean        24.405775
std         14.708242
min          0.000000
25%         16.000000
50%         27.000000
75%         35.000000
max         69.000000
Name: ACW (Sec), dtype: float64

                  count       mean       std   min   25%   50%   75%   max
Answered (Y/N)
N                7560.0   0.000000  0.000000   0.0   0.0   0.0   0.0   0.0
Y               32440.0  30.093434  9.776645  10.0  23.0  30.0  37.0  69.0

In [222]:
def duration_to_seconds(value):

    if pd.isna(value):
        return np.nan

    h, m, s = map(int, str(value).split(":"))

    return h*3600 + m*60 + s

In [223]:
for df in [fact_2021_full, fact_2022, fact_2023]:

    df["Talk Time (Sec)"] = (
        df["AvgTalkDuration"]
        .apply(duration_to_seconds)
    )

In [224]:
fact_2023[
[
"AvgTalkDuration",
"Talk Time (Sec)"
]
].sample(15)

      AvgTalkDuration  Talk Time (Sec)
34228             NaN              NaN
28733        00:05:34            334.0
5691         00:04:08            248.0
21514        00:04:38            278.0
15470        00:04:03            243.0
39624        00:06:39            399.0
22213        00:01:34             94.0
12784        00:06:38            398.0
30100             NaN              NaN
36691        00:02:13            133.0
1679         00:05:11            311.0
6268         00:03:19            199.0
11571        00:01:40            100.0
23433        00:06:01            361.0
12807             NaN              NaN

In [225]:
for df in [fact_2021_full, fact_2022, fact_2023]:

    df["AHT (Sec)"] = (
        df["Talk Time (Sec)"]
        + df["Hold Time (Sec)"]
        + df["ACW (Sec)"]
    )

In [226]:
fact_2023[
[
"Talk Time (Sec)",
"Hold Time (Sec)",
"ACW (Sec)",
"AHT (Sec)"
]
].sample(20)

       Talk Time (Sec)  Hold Time (Sec)  ACW (Sec)  AHT (Sec)
18517              NaN                0          0        NaN
7491               NaN                0          0        NaN
16888              NaN                0          0        NaN
33715             63.0                0         13       76.0
37224            344.0                0         29      373.0
3167             323.0                0         10      333.0
17959            104.0                0         45      149.0
21064            157.0                0         25      182.0
20500            285.0                0         29      314.0
39569            114.0                0         12      126.0
18394            223.0                0         34      257.0
9892             368.0                0         34      402.0
25422             33.0               80         26      139.0
22442             60.0                0         37       97.0
24942             71.0                0         24       95.0
10473            185.0                0         34      219.0
14586            154.0                0         12      166.0
31646            259.0                0         40      299.0
22436            370.0                0         18      388.0
5473             135.0               18         37      190.0

In [227]:
fact_2023[
    [
        "Answered (Y/N)",
        "AvgTalkDuration",
        "Talk Time (Sec)",
        "AHT (Sec)"
    ]
].sample(20)

      Answered (Y/N) AvgTalkDuration  Talk Time (Sec)  AHT (Sec)
33906              Y        00:02:42            162.0      197.0
28290              N             NaN              NaN        NaN
33293              Y        00:01:20             80.0       94.0
6647               Y        00:03:45            225.0      272.0
842                Y        00:05:56            356.0      387.0
7200               Y        00:05:11            311.0      344.0
2768               Y        00:00:51             51.0      159.0
7727               Y        00:01:26             86.0      106.0
20341              Y        00:05:32            332.0      401.0
35548              Y        00:06:23            383.0      461.0
28304              Y        00:05:43            343.0      362.0
6817               Y        00:00:45             45.0       66.0
27209              Y        00:04:40            280.0      325.0
34291              Y        00:04:49            289.0      320.0
26925              Y        00:05:20            320.0      390.0
29338              Y        00:01:56            116.0      150.0
30700              Y        00:05:07            307.0      344.0
15406              Y        00:06:27            387.0      491.0
12684              Y        00:05:45            345.0      360.0
27856              N             NaN              NaN        NaN

In [245]:
SLA_TARGET = 95

In [246]:
def generate_sla_status(answered, speed):

    # المكالمة غير المجابة تعتبر خارج الـ SLA
    if answered == "N":
        return "Breached"

    if pd.isna(speed):
        return "Breached"

    if speed <= SLA_TARGET:
        return "Within SLA"

    return "Breached"

In [247]:
def add_sla_status(df):

    df = df.copy()

    df["SLA Status"] = df.apply(
        lambda row: generate_sla_status(
            row["Answered (Y/N)"],
            row["Speed of answer in seconds"]
        ),
        axis=1
    )

    return df

In [248]:
fact_2021_full = add_sla_status(fact_2021_full)

fact_2022 = add_sla_status(fact_2022)

fact_2023 = add_sla_status(fact_2023)

In [249]:
for year_name, data in {
    "2021": fact_2021_full,
    "2022": fact_2022,
    "2023": fact_2023
}.items():

    print("=" * 50)
    print(year_name)
    print("=" * 50)

    print(
        data["SLA Status"]
        .value_counts(normalize=True)
        .mul(100)
        .round(2)
    )

    print()

==================================================
2021
==================================================
SLA Status
Within SLA    60.04
Breached      39.96
Name: proportion, dtype: float64

==================================================
2022
==================================================
SLA Status
Within SLA    59.93
Breached      40.07
Name: proportion, dtype: float64

==================================================
2023
==================================================
SLA Status
Within SLA    60.18
Breached      39.82
Name: proportion, dtype: float64

In [233]:
fact_2023["Speed of answer in seconds"].describe()

count    32440.000000
mean        67.281134
std         33.677666
min         10.000000
25%         38.000000
50%         68.000000
75%         96.000000
max        125.000000
Name: Speed of answer in seconds, dtype: float64

In [250]:
import numpy as np

fcr_probability = {
    "Streaming": 0.90,
    "Admin Support": 0.85,
    "Payment related": 0.80,
    "Contract related": 0.75,
    "Technical Support": 0.60
}

In [251]:
def generate_fcr(answered, resolved, topic):

    if answered == "N":
        return "No"

    if resolved == "N":
        return "No"

    probability = fcr_probability.get(topic, 0.75)

    return "Yes" if np.random.rand() < probability else "No"

In [252]:
def add_fcr(df):

    df = df.copy()

    df["FCR"] = df.apply(
        lambda row: generate_fcr(
            row["Answered (Y/N)"],
            row["Resolved"],
            row["Topic"]
        ),
        axis=1
    )

    return df

In [253]:
fact_2021_full = add_fcr(fact_2021_full)

fact_2022 = add_fcr(fact_2022)

fact_2023 = add_fcr(fact_2023)

In [254]:
for year_name, data in {
    "2021": fact_2021_full,
    "2022": fact_2022,
    "2023": fact_2023
}.items():

    print("=" * 50)
    print(year_name)
    print("=" * 50)

    print(data["FCR"].value_counts(normalize=True).mul(100).round(2))

    print("\nFCR by Topic")

    print(
        pd.crosstab(
            data["Topic"],
            data["FCR"],
            normalize="index"
        ).round(3) * 100
    )

    print()

==================================================
2021
==================================================
FCR
Yes    57.28
No     42.72
Name: proportion, dtype: float64

FCR by Topic
FCR                  No   Yes
Topic
Admin Support      36.7  63.3
Contract related   44.8  55.2
Payment related    42.0  58.0
Streaming          33.6  66.4
Technical Support  56.3  43.7

==================================================
2022
==================================================
FCR
Yes    56.89
No     43.11
Name: proportion, dtype: float64

FCR by Topic
FCR                  No   Yes
Topic
Admin Support      36.3  63.7
Contract related   46.3  53.7
Payment related    43.0  57.0
Streaming          33.0  67.0
Technical Support  56.7  43.3

==================================================
2023
==================================================
FCR
Yes    57.06
No     42.94
Name: proportion, dtype: float64

FCR by Topic
FCR                  No   Yes
Topic
Admin Support      37.3  62.7
Contract related   44.1  55.9
Payment related    42.6  57.4
Streaming          34.0  66.0
Technical Support  56.5  43.5

In [255]:
transfer_probability = {
    "Technical Support": 0.20,
    "Contract related": 0.12,
    "Payment related": 0.08,
    "Admin Support": 0.05,
    "Streaming": 0.03
}

In [256]:
import numpy as np

def generate_transfer(topic, resolved, fcr):

    probability = transfer_probability.get(topic, 0.08)

    if fcr == "No":
        probability += 0.15

    if resolved == "N":
        probability += 0.20

    probability = min(probability, 0.90)

    return "Yes" if np.random.rand() < probability else "No"

In [257]:
def add_transfer_flag(df):

    df = df.copy()

    df["Transfer Flag"] = df.apply(
        lambda row: generate_transfer(
            row["Topic"],
            row["Resolved"],
            row["FCR"]
        ),
        axis=1
    )

    return df

In [258]:
fact_2021_full = add_transfer_flag(fact_2021_full)

fact_2022 = add_transfer_flag(fact_2022)

fact_2023 = add_transfer_flag(fact_2023)

In [259]:
for year_name, data in {
    "2021": fact_2021_full,
    "2022": fact_2022,
    "2023": fact_2023
}.items():

    print("=" * 50)
    print(year_name)
    print("=" * 50)

    print(
        data["Transfer Flag"]
        .value_counts(normalize=True)
        .mul(100)
        .round(2)
    )

    print()

==================================================
2021
==================================================
Transfer Flag
No     78.87
Yes    21.13
Name: proportion, dtype: float64

==================================================
2022
==================================================
Transfer Flag
No     78.06
Yes    21.94
Name: proportion, dtype: float64

==================================================
2023
==================================================
Transfer Flag
No     78.06
Yes    21.94
Name: proportion, dtype: float64

In [260]:
pd.crosstab(
    fact_2023["Topic"],
    fact_2023["Transfer Flag"],
    normalize="index"
).round(3) * 100

Transfer Flag        No   Yes
Topic
Admin Support      83.4  16.6
Contract related   76.4  23.6
Payment related    78.8  21.2
Streaming          86.5  13.5
Technical Support  65.5  34.5

In [261]:
import numpy as np

def generate_escalation(topic,
                        transfer,
                        resolved,
                        fcr,
                        satisfaction):

    probability = 0.02

    if transfer == "Yes":
        probability += 0.25

    if fcr == "No":
        probability += 0.20

    if resolved == "N":
        probability += 0.30

    if topic == "Technical Support":
        probability += 0.10

    if pd.notna(satisfaction):
        if satisfaction <= 2:
            probability += 0.25

    probability = min(probability, 0.95)

    return "Yes" if np.random.rand() < probability else "No"

In [262]:
def add_escalation(df):

    df = df.copy()

    df["Escalation"] = df.apply(
        lambda row: generate_escalation(
            row["Topic"],
            row["Transfer Flag"],
            row["Resolved"],
            row["FCR"],
            row["Satisfaction rating"]
        ),
        axis=1
    )

    return df

In [263]:
fact_2021_full = add_escalation(fact_2021_full)

fact_2022 = add_escalation(fact_2022)

fact_2023 = add_escalation(fact_2023)

In [264]:
for year_name, data in {
    "2021": fact_2021_full,
    "2022": fact_2022,
    "2023": fact_2023
}.items():

    print("=" * 50)
    print(year_name)
    print("=" * 50)

    print(
        data["Escalation"]
        .value_counts(normalize=True)
        .mul(100)
        .round(2)
    )

    print()

==================================================
2021
==================================================
Escalation
No     69.84
Yes    30.15
Name: proportion, dtype: float64

==================================================
2022
==================================================
Escalation
No     69.54
Yes    30.46
Name: proportion, dtype: float64

==================================================
2023
==================================================
Escalation
No     70.26
Yes    29.74
Name: proportion, dtype: float64

In [265]:
pd.crosstab(
    fact_2023["Transfer Flag"],
    fact_2023["Escalation"],
    normalize="index"
).round(3) * 100

Escalation       No   Yes
Transfer Flag
No             80.1  19.9
Yes            35.4  64.6

In [266]:
import numpy as np

def generate_login_hours(shift):

    if shift == "Morning":
        return round(np.random.uniform(8.0, 9.0), 2)

    elif shift == "Evening":
        return round(np.random.uniform(8.0, 9.0), 2)

    else:
        return round(np.random.uniform(7.5, 8.5), 2)

In [267]:
def add_login_hours(df):

    df = df.copy()

    df["Login Hours"] = df["Shift"].apply(generate_login_hours)

    return df

In [268]:
fact_2021_full = add_login_hours(fact_2021_full)

fact_2022 = add_login_hours(fact_2022)

fact_2023 = add_login_hours(fact_2023)

In [269]:
for year_name, data in {
    "2021": fact_2021_full,
    "2022": fact_2022,
    "2023": fact_2023
}.items():

    print("=" * 50)
    print(year_name)
    print("=" * 50)

    print(data["Login Hours"].describe())

    print()

    print(data.groupby("Shift")["Login Hours"].describe())

    print()

==================================================
2021
==================================================
count    20000.000000
mean         8.499674
std          0.287378
min          8.000000
25%          8.250000
50%          8.500000
75%          8.750000
max          9.000000
Name: Login Hours, dtype: float64

           count      mean       std  min   25%   50%   75%  max
Shift
Evening   4652.0  8.506472  0.282675  8.0  8.27  8.50  8.75  9.0
Morning  15348.0  8.497613  0.288766  8.0  8.25  8.49  8.75  9.0

==================================================
2022
==================================================
count    25000.000000
mean         8.506212
std          0.288388
min          8.000000
25%          8.260000
50%          8.510000
75%          8.760000
max          9.000000
Name: Login Hours, dtype: float64

           count      mean       std  min   25%   50%   75%  max
Shift
Evening   5735.0  8.508963  0.290895  8.0  8.26  8.51  8.77  9.0
Morning  19265.0  8.505393  0.287640  8.0  8.26  8.51  8.76  9.0

==================================================
2023
==================================================
count    40000.000000
mean         8.498492
std          0.288020
min          8.000000
25%          8.250000
50%          8.500000
75%          8.750000
max          9.000000
Name: Login Hours, dtype: float64

           count      mean       std  min   25%   50%   75%  max
Shift
Evening   9390.0  8.494553  0.288036  8.0  8.25  8.49  8.75  9.0
Morning  30610.0  8.499701  0.288008  8.0  8.25  8.50  8.75  9.0

In [270]:
print("=" * 80)
print("2021")
print("=" * 80)
fact_2021_full.info()

print("\n")

print("=" * 80)
print("2022")
print("=" * 80)
fact_2022.info()

print("\n")

print("=" * 80)
print("2023")
print("=" * 80)
fact_2023.info()

================================================================================
2021
================================================================================
<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Call Id                     20000 non-null  str
 1   AgentID                     20000 non-null  str
 2   Agent                       20000 non-null  str
 3   Date                        20000 non-null  datetime64[us]
 4   Time                        20000 non-null  object
 5   Topic                       20000 non-null  str
 6   Answered (Y/N)              20000 non-null  str
 7   Resolved                    20000 non-null  str
 8   Speed of answer in seconds  16216 non-null  float64
 9   AvgTalkDuration             16216 non-null  object
 10  Satisfaction rating         16216 non-null  float64
 11  Team                        20000 non-null  str
 12  Team Leader                 20000 non-null  str
 13  Department                  20000 non-null  str
 14  Shift                       20000 non-null  str
 15  Queue Time (Sec)            20000 non-null  int64
 16  Hold Time (Sec)             20000 non-null  int64
 17  ACW (Sec)                   20000 non-null  int64
 18  Talk Time (Sec)             16216 non-null  float64
 19  AHT (Sec)                   16216 non-null  float64
 20  SLA Status                  20000 non-null  str
 21  FCR                         20000 non-null  str
 22  Transfer Flag               20000 non-null  str
 23  Escalation                  20000 non-null  str
 24  Login Hours                 20000 non-null  float64
dtypes: datetime64[us](1), float64(5), int64(3), object(2), str(14)
memory usage: 3.8+ MB


================================================================================
2022
================================================================================
<class 'pandas.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Call Id                     25000 non-null  str
 1   AgentID                     25000 non-null  str
 2   Agent                       25000 non-null  str
 3   Date                        25000 non-null  datetime64[us]
 4   Time                        25000 non-null  object
 5   Topic                       25000 non-null  str
 6   Answered (Y/N)              25000 non-null  str
 7   Resolved                    25000 non-null  str
 8   Speed of answer in seconds  20208 non-null  float64
 9   AvgTalkDuration             20208 non-null  object
 10  Satisfaction rating         20208 non-null  float64
 11  Team                        25000 non-null  str
 12  Team Leader                 25000 non-null  str
 13  Department                  25000 non-null  str
 14  Shift                       25000 non-null  str
 15  Queue Time (Sec)            25000 non-null  int64
 16  Hold Time (Sec)             25000 non-null  int64
 17  ACW (Sec)                   25000 non-null  int64
 18  Talk Time (Sec)             20208 non-null  float64
 19  AHT (Sec)                   20208 non-null  float64
 20  SLA Status                  25000 non-null  str
 21  FCR                         25000 non-null  str
 22  Transfer Flag               25000 non-null  str
 23  Escalation                  25000 non-null  str
 24  Login Hours                 25000 non-null  float64
dtypes: datetime64[us](1), float64(5), int64(3), object(2), str(14)
memory usage: 4.8+ MB


================================================================================
2023
================================================================================
<class 'pandas.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Call Id                     40000 non-null  str
 1   AgentID                     40000 non-null  str
 2   Agent                       40000 non-null  str
 3   Date                        40000 non-null  datetime64[us]
 4   Time                        40000 non-null  object
 5   Topic                       40000 non-null  str
 6   Answered (Y/N)              40000 non-null  str
 7   Resolved                    40000 non-null  str
 8   Speed of answer in seconds  32440 non-null  float64
 9   AvgTalkDuration             32440 non-null  object
 10  Satisfaction rating         32440 non-null  float64
 11  Team                        40000 non-null  str
 12  Team Leader                 40000 non-null  str
 13  Department                  40000 non-null  str
 14  Shift                       40000 non-null  str
 15  Queue Time (Sec)            40000 non-null  int64
 16  Hold Time (Sec)             40000 non-null  int64
 17  ACW (Sec)                   40000 non-null  int64
 18  Talk Time (Sec)             32440 non-null  float64
 19  AHT (Sec)                   32440 non-null  float64
 20  SLA Status                  40000 non-null  str
 21  FCR                         40000 non-null  str
 22  Transfer Flag               40000 non-null  str
 23  Escalation                  40000 non-null  str
 24  Login Hours                 40000 non-null  float64
dtypes: datetime64[us](1), float64(5), int64(3), object(2), str(14)
memory usage: 7.6+ MB

In [271]:
print("2021:", fact_2021_full.shape)
print("2022:", fact_2022.shape)
print("2023:", fact_2023.shape)

2021: (20000, 25)
2022: (25000, 25)
2023: (40000, 25)

In [272]:
print(fact_2021_full.isnull().sum())

print("=" * 80)

print(fact_2022.isnull().sum())

print("=" * 80)

print(fact_2023.isnull().sum())

Call Id                          0
AgentID                          0
Agent                            0
Date                             0
Time                             0
Topic                            0
Answered (Y/N)                   0
Resolved                         0
Speed of answer in seconds    3784
AvgTalkDuration               3784
Satisfaction rating           3784
Team                             0
Team Leader                      0
Department                       0
Shift                            0
Queue Time (Sec)                 0
Hold Time (Sec)                  0
ACW (Sec)                        0
Talk Time (Sec)               3784
AHT (Sec)                     3784
SLA Status                       0
FCR                              0
Transfer Flag                    0
Escalation                       0
Login Hours                      0
dtype: int64
================================================================================
Call Id                          0
AgentID                          0
Agent                            0
Date                             0
Time                             0
Topic                            0
Answered (Y/N)                   0
Resolved                         0
Speed of answer in seconds    4792
AvgTalkDuration               4792
Satisfaction rating           4792
Team                             0
Team Leader                      0
Department                       0
Shift                            0
Queue Time (Sec)                 0
Hold Time (Sec)                  0
ACW (Sec)                        0
Talk Time (Sec)               4792
AHT (Sec)                     4792
SLA Status                       0
FCR                              0
Transfer Flag                    0
Escalation                       0
Login Hours                      0
dtype: int64
================================================================================
Call Id                          0
AgentID                          0
Agent                            0
Date                             0
Time                             0
Topic                            0
Answered (Y/N)                   0
Resolved                         0
Speed of answer in seconds    7560
AvgTalkDuration               7560
Satisfaction rating           7560
Team                             0
Team Leader                      0
Department                       0
Shift                            0
Queue Time (Sec)                 0
Hold Time (Sec)                  0
ACW (Sec)                        0
Talk Time (Sec)               7560
AHT (Sec)                     7560
SLA Status                       0
FCR                              0
Transfer Flag                    0
Escalation                       0
Login Hours                      0
dtype: int64

In [273]:
fact_calls.columns.tolist()

['Call Id',
 'AgentID',
 'Agent',
 'Date',
 'Time',
 'Topic',
 'Answered (Y/N)',
 'Resolved',
 'Speed of answer in seconds',
 'AvgTalkDuration',
 'Satisfaction rating',
 'Team',
 'Team Leader']

In [274]:
fact_calls.shape

(85000, 13)

In [275]:
fact_calls.columns.tolist()

['Call Id',
 'AgentID',
 'Agent',
 'Date',
 'Time',
 'Topic',
 'Answered (Y/N)',
 'Resolved',
 'Speed of answer in seconds',
 'AvgTalkDuration',
 'Satisfaction rating',
 'Team',
 'Team Leader']

In [276]:
dim_agents.columns.tolist()

['AgentID',
 'Agent',
 'Hire Date',
 'Exit Date',
 'Gender',
 'Employment Status',
 'Hire Year',
 'Team',
 'Team Leader']

In [277]:
fact_2021_full
fact_2022
fact_2023

,Call Id,AgentID,Agent,Date,Time,Topic,Answered (Y/N),Resolved,Speed of answer in seconds,AvgTalkDuration,...,Queue Time (Sec),Hold Time (Sec),ACW (Sec),Talk Time (Sec),AHT (Sec),SLA Status,FCR,Transfer Flag,Escalation,Login Hours
0,2023-000001,AG005,Mostafa Ahmed,2023-01-01,09:12:58,Technical Support,Y,N,70.0,00:04:02,...,58,0,14,242.0,256.0,Within SLA,No,Yes,Yes,8.93
1,2023-000002,AG011,Mahmoud Mohamed,2023-01-01,09:12:58,Contract related,Y,Y,109.0,00:02:23,...,11,0,29,143.0,172.0,Breached,No,No,Yes,8.00
2,2023-000003,AG022,Bishoy Samir,2023-01-01,09:12:58,Contract related,Y,Y,109.0,00:02:23,...,5,31,51,143.0,225.0,Breached,No,Yes,No,8.38
3,2023-000004,AG045,Hazem Hamdy,2023-01-01,09:12:58,Contract related,Y,Y,109.0,00:02:23,...,60,0,36,143.0,179.0,Breached,Yes,No,No,8.05
4,2023-000005,AG035,Ahmed Reda,2023-01-01,10:00:29,Payment related,Y,Y,95.0,00:01:00,...,53,0,21,60.0,81.0,Within SLA,Yes,No,No,8.26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39995,2023-039996,AG043,Salma Ahmed,2023-12-28,17:39:50,Contract related,N,N,NaN,NaN,...,76,0,0,NaN,NaN,Breached,No,Yes,Yes,8.71
39996,2023-039997,AG021,Aya Tarek,2023-12-28,17:52:48,Contract related,Y,Y,32.0,00:00:47,...,57,0,41,47.0,88.0,Within SLA,Yes,No,No,8.15
39997,2023-039998,AG068,Mostafa Salem,2023-12-28,17:57:07,Admin Support,Y,Y,74.0,00:06:08,...,51,0,42,368.0,410.0,Within SLA,Yes,No,No,8.58
39998,2023-039999,AG045,Hazem Hamdy,2023-12-28,17:58:34,Payment related,Y,Y,64.0,00:04:16,...,6,0,26,256.0,282.0,Within SLA,Yes,No,No,8.48
39999,2023-040000,AG073,Mahmoud Youssef,2023-12-28,17:58:34,Payment related,Y,Y,64.0,00:04:16,...,54,0,14,256.0,270.0,Within SLA,Yes,No,No,8.85

In [278]:
fact_calls = pd.concat(
    [fact_2021_full, fact_2022, fact_2023],
    ignore_index=True
)

fact_calls.to_csv("Fact_Calls.csv", index=False)

In [279]:
fact_calls.columns.tolist()

['Call Id',
 'AgentID',
 'Agent',
 'Date',
 'Time',
 'Topic',
 'Answered (Y/N)',
 'Resolved',
 'Speed of answer in seconds',
 'AvgTalkDuration',
 'Satisfaction rating',
 'Team',
 'Team Leader',
 'Department',
 'Shift',
 'Queue Time (Sec)',
 'Hold Time (Sec)',
 'ACW (Sec)',
 'Talk Time (Sec)',
 'AHT (Sec)',
 'SLA Status',
 'FCR',
 'Transfer Flag',
 'Escalation',
 'Login Hours']

In [280]:
fact_calls.shape

(85000, 25)

In [281]:
fact_calls = pd.concat(
    [fact_2021_full, fact_2022, fact_2023],
    ignore_index=True
)

fact_calls.shape

(85000, 25)

In [282]:
daily = (
    fact_calls
    .groupby(["AgentID", "Date"])
    .agg(
        Agent=("Agent", "first"),
        Team=("Team", "first"),
        Team_Leader=("Team Leader", "first"),
        Login_Hours=("Login Hours", "first"),
        Calls=("Call Id", "count"),
        Total_AHT=("AHT (Sec)", "sum"),
        Avg_AHT=("AHT (Sec)", "mean"),
        Total_Talk_Time=("Talk Time (Sec)", "sum"),
        Total_Hold_Time=("Hold Time (Sec)", "sum"),
        Total_ACW=("ACW (Sec)", "sum")
    )
    .reset_index()
)

daily.head()

,AgentID,Date,Agent,Team,Team_Leader,Login_Hours,Calls,Total_AHT,Avg_AHT,Total_Talk_Time,Total_Hold_Time,Total_ACW
0,AG001,2021-01-01,Ahmed Mohamed,Team A,Mohamed Hassan,8.95,5,1152.0,288.0,959.0,104,89
1,AG001,2021-01-02,Ahmed Mohamed,Team A,Mohamed Hassan,8.20,8,1890.0,270.0,1528.0,157,205
2,AG001,2021-01-03,Ahmed Mohamed,Team A,Mohamed Hassan,8.58,7,1151.0,230.2,955.0,58,138
3,AG001,2021-01-04,Ahmed Mohamed,Team A,Mohamed Hassan,8.36,6,1881.0,313.5,1532.0,167,182
4,AG001,2021-01-05,Ahmed Mohamed,Team A,Mohamed Hassan,8.31,6,1128.0,225.6,798.0,201,129

In [283]:
daily.shape

(28966, 12)

In [284]:
import numpy as np

np.random.seed(42)

daily["Break_Time_Min"] = np.random.randint(
    45,
    76,
    len(daily)
)

In [285]:
daily["Available_Time_Min"] = (
    daily["Login_Hours"] * 60
) - daily["Break_Time_Min"]

In [286]:
daily["Occupancy"] = (
    daily["Total_AHT"]
    / daily["Available_Time_Min"]
)

In [287]:
daily["Occupancy"] = (
    daily["Occupancy"]
        .clip(0, 1)
        .round(3)
)

In [288]:
daily["Utilization"] = (
    daily["Total_AHT"]
    /
    (daily["Login_Hours"] * 60)
)

In [289]:
daily["Utilization"] = (
    daily["Utilization"]
        .clip(0, 1)
        .round(3)
)

In [290]:
daily[
    [
        "Login_Hours",
        "Break_Time_Min",
        "Available_Time_Min",
        "Calls",
        "Occupancy",
        "Utilization"
    ]
].describe()

,Login_Hours,Break_Time_Min,Available_Time_Min,Calls,Occupancy,Utilization
count,28966.000000,28966.000000,28966.000000,28966.000000,28966.000000,28966.000000
mean,8.501970,60.097286,450.020928,2.934475,0.758084,0.723758
std,0.288414,8.892289,19.480575,2.846069,0.325338,0.330442
min,8.000000,45.000000,405.000000,1.000000,0.000000,0.000000
25%,8.250000,52.000000,435.000000,1.000000,0.550000,0.486000
50%,8.500000,60.000000,450.000000,2.000000,0.990000,0.871000
75%,8.750000,68.000000,465.000000,3.000000,1.000000,1.000000
max,9.000000,75.000000,495.000000,47.000000,1.000000,1.000000

In [291]:
import numpy as np

np.random.seed(42)

# Occupancy
daily["Occupancy"] = (
    np.random.normal(
        loc=0.78,
        scale=0.08,
        size=len(daily)
    )
    .clip(0.55, 0.95)
    .round(3)
)

# Utilization
daily["Utilization"] = (
    daily["Occupancy"]
    - np.random.uniform(
        0.03,
        0.10,
        len(daily)
    )
).clip(0.50, 0.90).round(3)

In [292]:
daily[
    ["Occupancy", "Utilization"]
].describe()

          Occupancy   Utilization
count  28966.000000  28966.000000
mean       0.779563      0.714589
std        0.078539      0.080702
min        0.550000      0.500000
25%        0.726000      0.659000
50%        0.780000      0.715000
75%        0.834000      0.770000
max        0.950000      0.900000

In [293]:
fact_calls["AgentID"].nunique()

100

In [294]:
dim_agents["AgentID"].nunique()

100

In [295]:
daily["AgentID"].nunique()

100

In [296]:
daily["Agent"].value_counts().describe()

count     98.000000
mean     295.571429
std      210.194510
min       10.000000
25%      145.250000
50%      239.000000
75%      426.750000
max      899.000000
Name: count, dtype: float64

In [297]:
daily["Calls"].describe()

count    28966.000000
mean         2.934475
std          2.846069
min          1.000000
25%          1.000000
50%          2.000000
75%          3.000000
max         47.000000
Name: Calls, dtype: float64

In [298]:
daily.rename(
    columns={
        "Team_Leader": "Team Leader"
    },
    inplace=True
)

daily.to_csv(
    "Fact_Agent_Daily.csv",
    index=False
)